package net.divinerpg.helper.item;

import net.divinerpg.DivineRPG;
import net.divinerpg.helper.base.ItemDivineRPG;
import net.divinerpg.helper.base.ItemDivineRPGSword;
import net.divinerpg.item.ItemAngelicArmor;
import net.divinerpg.item.ItemAquaticArmor;
import net.divinerpg.item.ItemArlemiteArmor;
import net.divinerpg.item.ItemBlueBow;
import net.divinerpg.item.ItemDensos;
import net.divinerpg.item.ItemEliteRealmiteArmor;
import net.divinerpg.item.ItemFrostSword;
import net.divinerpg.item.ItemHordeHorn;
import net.divinerpg.item.ItemInfernalFlame;
import net.divinerpg.item.ItemInfernoBow;
import net.divinerpg.item.ItemInfernoSword;
import net.divinerpg.item.ItemKarot;
import net.divinerpg.item.ItemKrakenArmor;
import net.divinerpg.item.ItemMassivence;
import net.divinerpg.item.ItemMysteriousClock;
import net.divinerpg.item.ItemRealmiteArmor;
import net.divinerpg.item.ItemRupeeArmor;
import net.divinerpg.item.ItemSandSlash;
import net.divinerpg.item.ItemSerenadeDeath;
import net.divinerpg.item.ItemSerenadeGrowth;
import net.divinerpg.item.ItemSerenadeHealth;
import net.divinerpg.item.ItemSerenadeStriker;
import net.divinerpg.item.ItemShadowArmor;
import net.divinerpg.item.ItemShadowBow;
import net.divinerpg.item.ItemSlimeSword;
import net.divinerpg.item.ItemSoulFiend;
import net.divinerpg.item.ItemTwilightClock;
import net.divinerpg.item.ItemTwilightDemon;
import net.divinerpg.item.ItemVamacheron;
import net.divinerpg.item.ItemWatcher;
import net.divinerpg.item.tool.ToolAxe;
import net.divinerpg.item.tool.ToolHoe;
import net.divinerpg.item.tool.ToolPickaxe;
import net.divinerpg.item.tool.ToolShickaxe;
import net.divinerpg.item.tool.ToolShovel;
import net.divinerpg.item.tool.ToolSword;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class OverworldItemHelper {


    public static int HEAD = 0;
    public static int BODY = 1;
    public static int LEGS = 2;
    public static int BOOTS = 3;

	static String[] angelicDesc = {"12.5% Damage reduction", "Unbreakable", "Full Set: Allows flight", "Full Set: No fall damage"};
	static String[] realmiteDesc = {"8.25% Damage reduction", "Unbreakable"};
	static String[] eliteRealmiteDesc = {"12.5% Damage reduction", "Unbreakable", "Full Set: No fall damage"};
	static String[] arlemiteDesc = {"12.5% Damage reduction", "Unbreakable", "Full Set: 80% Ranged damage protection"};
	static String[] krakenDesc = {"7.5% Damage reduction", "Unbreakable", "Full Set: Breathe underwater"};
	static String[] rupeeDesc = {"13.75% Damage reduction", "Unbreakable", "Full Set: 80% Melee damage protection"};
	static String[] aquaticDesc = {"13.75% Damage reduction", "Unbreakable", "Full Set: Breathe underwater", "Full Set: Swim faster"};
	static String[] shadowDesc = {"15% Damage reduction", "Unbreakable", "Full Set: Move faster"};

    public static EnumToolMaterial rupee = EnumHelper.addToolMaterial("Rupee", 4, 3000, 12.0F, 7, 15);
    public static EnumToolMaterial arlemite = EnumHelper.addToolMaterial("Arlemite", 4, 3000, 15.0F, 7, 15);
    public static EnumToolMaterial realmite = EnumHelper.addToolMaterial("Realmite", 4, 3000, 15.0F, 7, 15);
    public static EnumToolMaterial Inferno = EnumHelper.addToolMaterial("infernosword", 0, -1, 0, 9, 22);
    public static EnumToolMaterial halite = EnumHelper.addToolMaterial("halite", 10, 3000, 0, 15, 22);
    public static EnumToolMaterial rupeeShick = EnumHelper.addToolMaterial("RupeeShick", 4, -1, 16.0F, 7, 15);
    public static EnumToolMaterial arlemiteShick = EnumHelper.addToolMaterial("ArlemiteShick", 4, 13000, 15.0F, 7, 15);
    public static EnumToolMaterial divineWood = EnumHelper.addToolMaterial("divineWood", 0, 59, 2.0F, 0, 15);
    public static EnumToolMaterial Massivence = EnumHelper.addToolMaterial("massivence", 0, 520, 2.0F, 5, 15);


    static EnumArmorMaterial angelicArmor = EnumHelper.addArmorMaterial("Angelic", 200, new int[] {3, 4, 3, 2}, 22);
    static EnumArmorMaterial realmiteArmor = EnumHelper.addArmorMaterial("realmite", 200, new int[] {3, 2, 3, 2}, 22);
    static EnumArmorMaterial arlemiteArmor = EnumHelper.addArmorMaterial("arlemite", 200, new int[] {3, 4, 3, 2}, 22);
    static EnumArmorMaterial rupeeArmor = EnumHelper.addArmorMaterial("rupee", 200, new int[] {3, 5, 3, 2}, 22);
    static EnumArmorMaterial shadow = EnumHelper.addArmorMaterial("shadow", 200, new int[] {3, 6, 3, 2}, 22);
    static EnumArmorMaterial aquatic = EnumHelper.addArmorMaterial("aquatic", 200, new int[] {3, 5, 3, 2}, 22);
    static EnumArmorMaterial angelic = EnumHelper.addArmorMaterial("Angelic", 200, new int[] {3, 4, 3, 2}, 22);
    static EnumArmorMaterial eliteRealmite = EnumHelper.addArmorMaterial("eliteRealmite", 200, new int[] {3, 4, 3, 2}, 22);
    static EnumArmorMaterial kraken = EnumHelper.addArmorMaterial("kraken", 200, new int[] {3, 2, 3, 2}, 22);

    public static final Item bloodGem = new ItemDivineRPG(1041).registerTextures("BloodGem").setUnlocalizedName("BloodGem").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeIngot = new ItemDivineRPG(1042).registerTextures("RupeeIngot").setUnlocalizedName("RupeeIngot").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteIngot = new ItemDivineRPG(1043).registerTextures("ArlemiteIngot").setUnlocalizedName("ArlemiteIngot").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteIngot = new ItemDivineRPG(1044).registerTextures("RealmiteIngot").setUnlocalizedName("RealmiteIngot").setCreativeTab(DivineRPG.Overworld);
    public static final Item netheriteIngot = new ItemDivineRPG(1045).registerTextures("NetheriteIngot").setUnlocalizedName("NetheriteIngot").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeShovel = new ToolShovel(1046, rupee).registerItemTexture("RupeeShovel").setUnlocalizedName("RupeeShovel").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeAxe = new ToolAxe(1047, rupee).registerItemTexture("RupeeAxe").setUnlocalizedName("RupeeAxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeHoe = new ToolHoe(1048, rupee).registerItemTexture("RupeeHoe").setUnlocalizedName("RupeeHoe").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeePickaxe = new ToolPickaxe(1049, rupee).registerItemTexture("RupeePickaxe").setUnlocalizedName("RupeePickaxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeSword = new ToolSword(1050, rupee).registerItemTexture("RupeeSword").setUnlocalizedName("RupeeSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteShovel = new ToolShovel(1051, arlemite).registerItemTexture("ArlemiteShovel").setUnlocalizedName("ArlemiteShovel").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteAxe = new ToolAxe(1052, arlemite).registerItemTexture("ArlemiteAxe").setUnlocalizedName("ArlemiteAxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteHoe = new ToolHoe(1053, arlemite).registerItemTexture("ArlemiteHoe").setUnlocalizedName("ArlemiteHoe").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemitePickaxe = new ToolPickaxe(1054, arlemite).registerItemTexture("ArlemitePickaxe").setUnlocalizedName("ArlemitePickaxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteSword = new ToolSword(1055, arlemite).registerItemTexture("ArlemiteSword").setUnlocalizedName("ArlemiteSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteShovel = new ToolShovel(1056, realmite).registerItemTexture("RealmiteShovel").setUnlocalizedName("RealmiteShovel").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteAxe = new ToolAxe(1057, realmite).registerItemTexture("RealmiteAxe").setUnlocalizedName("RealmiteAxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteHoe = new ToolHoe(1058, realmite).registerItemTexture("RealmiteHoe").setUnlocalizedName("RealmiteHoe").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmitePickaxe = new ToolPickaxe(1059, realmite).registerItemTexture("RealmitePickaxe").setUnlocalizedName("RealmitePickaxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteSword = new ToolSword(1060, realmite).registerItemTexture("RealmiteSword").setUnlocalizedName("RealmiteSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeShickaxe = new ToolShickaxe(1193, rupeeShick).registerShickaxeTextures("RupeeShickaxe").setUnlocalizedName("RupeeShickaxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteShickaxe = new ToolShickaxe(1194, arlemiteShick).registerShickaxeTextures("ArlemiteShickaxe").setUnlocalizedName("ArlemiteShickaxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item jungleShard = new ItemDivineRPG(1063).registerTextures("JungleShards").setUnlocalizedName("Jungle").setCreativeTab(DivineRPG.Overworld);
    public static final Item iceShard = new ItemDivineRPG(1064).registerTextures("IceShards").setUnlocalizedName("Ice").setCreativeTab(DivineRPG.Overworld);    
    public static final Item moltenShard = new ItemDivineRPG(1065).registerTextures("MoltenShards").setUnlocalizedName("Molten").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineShard = new ItemDivineRPG(1066).registerTextures("DivineShards").setUnlocalizedName("Divine").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderShard = new ItemDivineRPG(1067).registerTextures("EnderShards").setUnlocalizedName("Ender").setCreativeTab(DivineRPG.Overworld);
    public static final Item corruptedShard = new ItemDivineRPG(1068).registerTextures("CorruptedShards").setUnlocalizedName("Corrupted").setCreativeTab(DivineRPG.Overworld);
    public static final Item jungleStone = new ItemDivineRPG(1069).registerTextures("JungleStone").setUnlocalizedName("JungleS").setCreativeTab(DivineRPG.Overworld);
    public static final Item iceStone = new ItemDivineRPG(1070).registerTextures("IceStone").setUnlocalizedName("IceS").setCreativeTab(DivineRPG.Overworld);
    public static final Item moltenStone = new ItemDivineRPG(1071).registerTextures("MoltenStone").setUnlocalizedName("MoltenS").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderStone = new ItemDivineRPG(1072).registerTextures("EnderStone").setUnlocalizedName("EnderS").setCreativeTab(DivineRPG.Overworld);
    public static final Item corruptedStone = new ItemDivineRPG(1073).registerTextures("CorruptedStone").setUnlocalizedName("CorruptedS").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineStone = new ItemDivineRPG(1074).registerTextures("DivineStone").setUnlocalizedName("DivineS").setCreativeTab(DivineRPG.Overworld);
    public static final Item hellStoneIngot = new ItemDivineRPG(1075).registerTextures("HellStoneIngot").setUnlocalizedName("HellStoneIngot").setCreativeTab(DivineRPG.Overworld);
    public static final Item purpleBlaze = new ItemDivineRPG(1076).registerTextures("PurpleBlaze").setUnlocalizedName("PurpleBlaze").setCreativeTab(DivineRPG.Overworld);
    public static final Item infernoSword = new ItemInfernoSword(1077, Inferno).registerTextures("InfernoSword").setUnlocalizedName("InfernoSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item infernoBow = new ItemInfernoBow(1078).setUnlocalizedName("InfernoBow").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderSword = new ItemDivineRPGSword(1079, EnumHelper.addToolMaterial("endersword", 0, -1, 0, 23, 22), true).registerTextures("EnderSword").setUnlocalizedName("enderSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderSwordBlue = new ItemDivineRPGSword(1080, EnumHelper.addToolMaterial("endersword", 0, -1, 0, 23, 22), true).registerTextures("EnderSwordBlue").setUnlocalizedName("enderSwordBlue").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderSwordDark = new ItemDivineRPGSword(1081, EnumHelper.addToolMaterial("endersword", 0, -1, 0, 23, 22), true).registerTextures("EnderSwordBlack").setUnlocalizedName("enderSwordDark").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderSwordGreen = new ItemDivineRPGSword(1082, EnumHelper.addToolMaterial("endersword", 0, -1, 0, 23, 22), true).registerTextures("EnderSwordGreen").setUnlocalizedName("enderSwordGreen").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderSwordRed = new ItemDivineRPGSword(1083, EnumHelper.addToolMaterial("endersword", 0, -1, 0, 23, 22), true).registerTextures("EnderSwordRed").setUnlocalizedName("enderSwordRed").setCreativeTab(DivineRPG.Overworld);
    public static final Item enderSwordYellow = new ItemDivineRPGSword(1084, EnumHelper.addToolMaterial("endersword", 0, -1, 0, 23, 22), true).registerTextures("EnderSwordYellow").setUnlocalizedName("enderSwordYellow").setCreativeTab(DivineRPG.Overworld);
    public static final Item slimeSword = new ItemSlimeSword(1085, EnumHelper.addToolMaterial("slimesword", 0, 1000, 0, 11, 22)).registerTextures("SlimeSword").setUnlocalizedName("SlimeSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowBar = new ItemDivineRPG(1086).registerTextures("ShadowBar").setUnlocalizedName("ShadowB").setCreativeTab(DivineRPG.Overworld);
    public static final Item blueFireStone = new ItemDivineRPG(1087).registerTextures("BlueFireStone").setUnlocalizedName("BlueFireStone").setCreativeTab(DivineRPG.Overworld);
    public static final Item netheriteChunk = new ItemDivineRPG(1088).registerTextures("NetheriteChunk").setUnlocalizedName("Chunk").setCreativeTab(DivineRPG.Overworld);
    public static final Item legendaryEnderEye = new ItemDivineRPG(1089).registerTextures("LegendaryEnderEye").setUnlocalizedName("LEE").setCreativeTab(DivineRPG.Overworld);
    public static final Item angelicHelmet = new ItemAngelicArmor(1090, angelicArmor, 0, HEAD).setDescriptors(angelicDesc).setUnlocalizedName("Angelichelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item angelicBody = new ItemAngelicArmor(1091, angelicArmor, 1, BODY).setDescriptors(angelicDesc).setUnlocalizedName("Angelicbody").setCreativeTab(DivineRPG.Overworld);
    public static final Item angelicLegs = new ItemAngelicArmor(1092, angelicArmor, 2, LEGS).setDescriptors(angelicDesc).setUnlocalizedName("Angeliclegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item angelicBoots = new ItemAngelicArmor(1093, angelicArmor, 3, BOOTS).setDescriptors(angelicDesc).setUnlocalizedName("Angelicboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteHelmet = new ItemRealmiteArmor(1094, realmiteArmor, 0, HEAD).setDamageReduction(0.85D).setDescriptors(realmiteDesc).setUnlocalizedName("Realmitehelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteBody = new ItemRealmiteArmor(1095, realmiteArmor, 1, BODY).setDamageReduction(0.85D).setDescriptors(realmiteDesc).setUnlocalizedName("Realmitebody").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteLegs = new ItemRealmiteArmor(1096, realmiteArmor, 2, LEGS).setDamageReduction(0.85D).setDescriptors(realmiteDesc).setUnlocalizedName("Realmitelegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item realmiteBoots = new ItemRealmiteArmor(1097, realmiteArmor, 3, BOOTS).setDamageReduction(0.85D).setDescriptors(realmiteDesc).setUnlocalizedName("Realmiteboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteHelmet = new ItemArlemiteArmor(1098, arlemiteArmor, 0, HEAD).setDescriptors(arlemiteDesc).setUnlocalizedName("Arlemitehelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteBody = new ItemArlemiteArmor(1099, arlemiteArmor, 1, BODY).setDescriptors(arlemiteDesc).setUnlocalizedName("Arlemitebody").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteLegs = new ItemArlemiteArmor(1100, arlemiteArmor, 2, LEGS).setDescriptors(arlemiteDesc).setUnlocalizedName("Arlemitelegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item arlemiteBoots = new ItemArlemiteArmor(1101, arlemiteArmor, 3, BOOTS).setDescriptors(arlemiteDesc).setUnlocalizedName("Arlemiteboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeHelmet = new ItemRupeeArmor(1102, rupeeArmor, 0, HEAD).setDamageReduction(0.135D).setDescriptors(rupeeDesc).setUnlocalizedName("Rupeehelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeBody = new ItemRupeeArmor(1103, rupeeArmor, 1, BODY).setDamageReduction(0.135D).setDescriptors(rupeeDesc).setUnlocalizedName("Rupeebody").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeLegs = new ItemRupeeArmor(1104, rupeeArmor, 2, LEGS).setDamageReduction(0.135D).setDescriptors(rupeeDesc).setUnlocalizedName("Rupeelegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item rupeeBoots = new ItemRupeeArmor(1105, rupeeArmor, 3, BOOTS).setDamageReduction(0.135D).setDescriptors(rupeeDesc).setUnlocalizedName("Rupeeboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item infernalFlame = new ItemInfernalFlame(1106).registerTextures("InfernalFlame").setUnlocalizedName("Infernal").setCreativeTab(DivineRPG.Overworld);
    public static final Item baseSpawnCrystal = new ItemDivineRPG(1107).registerTextures("BaseSpawnCrystal").setUnlocalizedName("BaseSpawn").setCreativeTab(DivineRPG.Overworld);
    public static final Item spawnSoulFiend = new ItemSoulFiend(1108).registerTextures("SpawnSoulFiend").setUnlocalizedName("SpawnSoul").setCreativeTab(DivineRPG.Overworld);
    public static final Item spawnVamacheron = new ItemVamacheron(1109).registerTextures("SpawnVamacheron").setUnlocalizedName("SpawnVamach").setCreativeTab(DivineRPG.Overworld);
    public static final Item spawnTwilightDemon = new ItemTwilightDemon(1110).registerTextures("SpawnTwilightDemon").setUnlocalizedName("Twilight").setCreativeTab(DivineRPG.Overworld);
    public static final Item spawnKarot = new ItemKarot(1111).registerTextures("SpawnKarot").setUnlocalizedName("Karot").setCreativeTab(DivineRPG.Overworld);
    public static final Item spawnDensos = new ItemDensos(1112).registerTextures("SpawnDensos").setUnlocalizedName("Densos").setCreativeTab(DivineRPG.Overworld);
    public static final Item hordeHorn = new ItemHordeHorn(1113).registerTextures("HordeHorn").setUnlocalizedName("HordeHorn").setCreativeTab(DivineRPG.Overworld);
    public static final Item mysteriousClock = new ItemMysteriousClock(1114).registerTextures("MysteriousClock").setUnlocalizedName("Mysterious").setCreativeTab(DivineRPG.Overworld);
    public static final Item twilightClock = new ItemTwilightClock(1115).registerTextures("TwilightClock").setUnlocalizedName("TwilightClock").setCreativeTab(DivineRPG.Twilight);
    public static final Item watchingEye = new ItemDivineRPG(1116).registerTextures("WatchingEye").setUnlocalizedName("WatchingEye").setCreativeTab(DivineRPG.Overworld);
    public static final Item furyFire = new ItemDivineRPG(1117).registerTextures("FuryFire").setUnlocalizedName("FuryFire").setCreativeTab(DivineRPG.Overworld);
    public static final Item furyArrow = new ItemDivineRPG(1118).registerTextures("FuryArrow").setUnlocalizedName("FuryArrow").setCreativeTab(DivineRPG.Overworld);
    public static final Item callOfTheWatcher = new ItemWatcher(1119).registerTextures("CallOfTheWatcher").setUnlocalizedName("CallOfTheWatcher").setCreativeTab(DivineRPG.Overworld);
    public static final Item bluefirebow = new ItemBlueBow(1120).setUnlocalizedName("BluefireBow").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowHelmet = new ItemShadowArmor(1121, shadow, 0, HEAD).setDamageReduction(0.150D).setDescriptors(shadowDesc).setUnlocalizedName("Shadowhelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowBody = new ItemShadowArmor(1122, shadow, 1, BODY).setDamageReduction(0.150D).setDescriptors(shadowDesc).setUnlocalizedName("Shadowbody").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowLegs = new ItemShadowArmor(1123, shadow, 2, LEGS).setDamageReduction(0.150D).setDescriptors(shadowDesc).setUnlocalizedName("Shadowlegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowBoots = new ItemShadowArmor(1124, shadow, 3, BOOTS).setDamageReduction(0.150D).setDescriptors(shadowDesc).setUnlocalizedName("Shadowboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item aquaticHelmet = new ItemAquaticArmor(1125, aquatic, 0, HEAD).setDamageReduction(0.135D).setDescriptors(aquaticDesc).setUnlocalizedName("AquastriveHelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item aquaticBody = new ItemAquaticArmor(1126, aquatic, 1, BODY).setDamageReduction(0.135D).setDescriptors(aquaticDesc).setUnlocalizedName("AquastriveBody").setCreativeTab(DivineRPG.Overworld);
    public static final Item aquaticLegs = new ItemAquaticArmor(1127, aquatic, 2, LEGS).setDamageReduction(0.135D).setDescriptors(aquaticDesc).setUnlocalizedName("AquastriveLegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item aquaticBoots = new ItemAquaticArmor(1128, aquatic, 3, BOOTS).setDamageReduction(0.135D).setDescriptors(aquaticDesc).setUnlocalizedName("AquastriveBoots").setCreativeTab(DivineRPG.Overworld);
    public static final Item krakenSkin = new ItemDivineRPG(1129).registerTextures("KrakenSkin").setUnlocalizedName("KrakS").setCreativeTab(DivineRPG.Overworld);
    public static final Item healingStone = new ItemDivineRPG(1130).registerTextures("HealingStone").setUnlocalizedName("HS").setCreativeTab(DivineRPG.Overworld);
    public static final Item krakenScale = new ItemDivineRPG(1131).registerTextures("KrakenScale").setUnlocalizedName("krakenScale").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowStone = new ItemDivineRPG(1132).registerTextures("ShadowStone").setUnlocalizedName("shadowStone").setCreativeTab(DivineRPG.Overworld);
    public static final Item homeTeleporter = new ItemDivineRPG(1133).registerTextures("TeleportationCrystal").setUnlocalizedName("homeTeleporter").setCreativeTab(DivineRPG.Overworld);
    public static final Item massivence = new ItemMassivence(1134, Massivence).registerTextures("Massivence").setUnlocalizedName("Massivence").setCreativeTab(DivineRPG.Overworld);
    public static final Item palavence = new ItemMassivence(1135, EnumToolMaterial.STONE).registerTextures("Palavence").setUnlocalizedName("Palavence").setCreativeTab(DivineRPG.Overworld);
    public static final Item aquaticTrident = new ItemDivineRPGSword(1136, EnumHelper.addToolMaterial("aquatictrident", 0, 7000, 0, 15, 22)).registerTextures("AquaticTrident").setUnlocalizedName("AquaticTrident").setCreativeTab(DivineRPG.Overworld);
    public static final Item oceanKnife = new ItemDivineRPGSword(1137, EnumHelper.addToolMaterial("aquaticknife", 0, 2000, 0, 14, 22)).registerTextures("AquaticKnife").setUnlocalizedName("AquaticKnife").setCreativeTab(DivineRPG.Overworld);
    public static final Item aquaton = new ItemDivineRPGSword(1138, EnumHelper.addToolMaterial("aquaton", 0, 10000, 0, 18, 22)).registerTextures("Aquaton").setUnlocalizedName("Aquaton").setCreativeTab(DivineRPG.Overworld);
    public static final Item sharkSword = new ItemDivineRPGSword(1139, EnumHelper.addToolMaterial("sharksword", 0, 2000, 0, 11, 22)).registerTextures("SharkSword").setUnlocalizedName("SharkSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item crabclawMaul = new ItemDivineRPGSword(1140, EnumHelper.addToolMaterial("crabclawmaul", 0, 8000, 0, 6, 22), true).registerTextures("CrabClawMaul").setUnlocalizedName("CrabClawMaul").setCreativeTab(DivineRPG.Overworld);	
    public static final Item deathBringer = new ItemDivineRPGSword(1141, EnumHelper.addToolMaterial("deathbringer", 0, 6000, 0, 13, 22)).registerTextures("DeathBringer").setUnlocalizedName("DeathBringer").setCreativeTab(DivineRPG.Overworld);
    public static final Item corruptedMaul = new ItemDivineRPGSword(1142, EnumHelper.addToolMaterial("corruptedmaul", 0, 6000, 0, 18, 22)).registerTextures("CorruptedMaul").setUnlocalizedName("CorruptedMaul").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineSword = new ItemDivineRPGSword(1143, EnumHelper.addToolMaterial("divinesword", 0, -1, 0, 29, 22), true).registerTextures("DivineSword").setUnlocalizedName("DivineSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item moltenSword = new ItemDivineRPGSword(1144, EnumHelper.addToolMaterial("moltensword", 0, 5000, 0, 10, 22)).registerTextures("MoltenSword").setUnlocalizedName("MoltenSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item bowHeadAnchor = new ItemDivineRPG(1145).registerTextures("BowHeadAnchor").setUnlocalizedName("BowHeadAnchor").setCreativeTab(DivineRPG.Overworld);
    public static final Item sharkAnchor = new ItemDivineRPG(1146).registerTextures("SharkAnchor").setUnlocalizedName("SharkAnchor").setCreativeTab(DivineRPG.Overworld);
    public static final Item crabAnchor = new ItemDivineRPG(1147).registerTextures("CrabAnchor").setUnlocalizedName("CrabAnchor").setCreativeTab(DivineRPG.Overworld);
    public static final Item scythe = new ItemDivineRPG(1148).registerTextures("Scythe").setUnlocalizedName("Scythe").setCreativeTab(DivineRPG.Overworld);
    public static final Item frostCannon = new ItemDivineRPG(1149).registerTextures("FrostCannon").setUnlocalizedName("FrostCannon").setCreativeTab(DivineRPG.Overworld);
    public static final Item soundOfMusic = new ItemDivineRPG(1150).registerTextures("SoundOfMusic").setUnlocalizedName("SoundOfMusic").setCreativeTab(DivineRPG.Overworld);
    public static final Item crabClawCannon = new ItemDivineRPG(1151).registerTextures("CrabclawCannon").setUnlocalizedName("CrabclawCannon").setCreativeTab(DivineRPG.Overworld);
    public static final Item bowheadCannon = new ItemDivineRPG(1152).registerTextures("BowHeadCannon").setUnlocalizedName("BowHeadCannon").setCreativeTab(DivineRPG.Overworld);
    public static final Item maelstrom = new ItemDivineRPG(1153).registerTextures("MaelStrom").setUnlocalizedName("MaelStrom").setCreativeTab(DivineRPG.Overworld);
    public static final Item ghastCannon = new ItemDivineRPG(1154).registerTextures("GhastCannon").setUnlocalizedName("GhastCannon").setCreativeTab(DivineRPG.Overworld);
    public static final Item corruptCannon = new ItemDivineRPG(1155).registerTextures("CorruptedCannon").setUnlocalizedName("CorruptedCannon").setCreativeTab(DivineRPG.Overworld);
    public static final Item serenadeStriker = new ItemSerenadeStriker(1156).registerTextures("SerenadeStriker").setUnlocalizedName("SerenadeStriker").setCreativeTab(DivineRPG.Overworld);
    public static final Item serenadeOfLife = new ItemSerenadeGrowth(1157).registerTextures("SerenadeOfLife").setUnlocalizedName("serenadeLife").setCreativeTab(DivineRPG.Overworld);
    public static final Item serenadeOfDeath = new ItemSerenadeDeath(1158).registerTextures("SerenadeOfDeath").setUnlocalizedName("SerenadeOfDeath").setCreativeTab(DivineRPG.Overworld);
    public static final Item serenadeHealth = new ItemSerenadeHealth(1159).registerTextures("SerenadeOfHealth").setUnlocalizedName("SerenadeOfHealth").setCreativeTab(DivineRPG.Overworld);
    public static final Item tomato = new ItemDivineRPG(1160).registerTextures("Tomato").setUnlocalizedName("Tomato").setCreativeTab(DivineRPG.Overworld);
    public static final Item tomatoSeeds = new ItemDivineRPG(1161).registerTextures("TomatoSeeds").setUnlocalizedName("TomatoSeeds").setCreativeTab(DivineRPG.Overworld);
    public static final Item sharkFin = new ItemDivineRPG(1162).registerTextures("SharkFin").setUnlocalizedName("SharkFin").setCreativeTab(DivineRPG.Overworld);
    public static final Item whaleFin = new ItemDivineRPG(1163).registerTextures("WhaleFin").setUnlocalizedName("WhaleFin").setCreativeTab(DivineRPG.Overworld);
    public static final Item purpleGlowBoneTree = new ItemDivineRPG(1164).registerTextures("PurpleGlowBoneSeeds").setUnlocalizedName("PurpleTree").setCreativeTab(DivineRPG.Overworld);
    public static final Item pinkGlowBoneTree = new ItemDivineRPG(1165).registerTextures("PinkGlowBoneSeeds").setUnlocalizedName("PinkTree").setCreativeTab(DivineRPG.Overworld);
    public static final Item jackOManBoots = new ItemDivineRPG(1166).registerTextures("JackOManBoots").setUnlocalizedName("JackOManBoots").setCreativeTab(DivineRPG.Overworld);
    public static final Item jackOManLegs = new ItemDivineRPG(1167).registerTextures("JackOManLegs").setUnlocalizedName("JackOManLegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item jackOManBody = new ItemDivineRPG(1168).registerTextures("JackOManBody").setUnlocalizedName("JackOManBody").setCreativeTab(DivineRPG.Overworld);
    public static final Item jackOManHead = new ItemDivineRPG(1169).registerTextures("JackOManHelmet").setUnlocalizedName("JackOManHelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item grimReaperHead = new ItemDivineRPG(1170).registerTextures("SkelemanHelmet").setUnlocalizedName("SkeleHelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item grimReaperBody = new ItemDivineRPG(1171).registerTextures("SkelemanBody").setUnlocalizedName("SkeleBody").setCreativeTab(DivineRPG.Overworld);
    public static final Item grimReaperLegs = new ItemDivineRPG(1172).registerTextures("SkelemanLegs").setUnlocalizedName("SkeleLegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item grimReaperBoots = new ItemDivineRPG(1173).registerTextures("SkelemanBoots").setUnlocalizedName("SkeleBoots").setCreativeTab(DivineRPG.Overworld);
    public static final Item bedrockMaul = new ItemDivineRPGSword(1174, 15, EnumHelper.addToolMaterial("bedrockmaul", 1, -1, 1.5F, 19, 22), true).registerTextures("BedrockMaul").setUnlocalizedName("bedrock").setCreativeTab(DivineRPG.Overworld);	
    public static final Item sandSlash = new ItemSandSlash(1175, EnumHelper.addToolMaterial("sandslash", 0, 100, 0, 32, 22)).setCreativeTab(DivineRPG.Overworld);
    public static final Item frostSword = new ItemFrostSword(1176, EnumHelper.addToolMaterial("frostsword", 0, 5000, 0, 10, 22)).registerTextures("FrostSword").setUnlocalizedName("FrostSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item bedrockSword = new ItemDivineRPGSword(1177, EnumHelper.addToolMaterial("bedrocksword", 0, 14000, 0, 13, 22)).registerTextures("BedrockSword").setUnlocalizedName("BedrockSword").setCreativeTab(DivineRPG.Overworld);
    public static final Item shadowBow = new ItemShadowBow(1178).setUnlocalizedName("ShadowBow").setCreativeTab(DivineRPG.Overworld);
    //public static final Item shuriken = new ItemShuriken(4397).registerTextures("Shuriken").setUnlocalizedName("Shuriken").setCreativeTab(DivineRPG.Overworld);
    //public static final Item vileStorm = new ItemVailStorm(4398).registerTextures("VileStorm").setUnlocalizedName("VileStorm").setCreativeTab(DivineRPG.Overworld);	
    public static final Item eliteRealmiteHelmet = new ItemEliteRealmiteArmor(1179, eliteRealmite, 0, HEAD).setDamageReduction(0.125D).setDescriptors(eliteRealmiteDesc).setUnlocalizedName("Eliterealmitehelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item eliteRealmiteBody = new ItemEliteRealmiteArmor(1180, eliteRealmite, 1, BODY).setDamageReduction(0.125D).setDescriptors(eliteRealmiteDesc).setUnlocalizedName("Eliterealmitebody").setCreativeTab(DivineRPG.Overworld);
    public static final Item eliteRealmiteLegs = new ItemEliteRealmiteArmor(1181, eliteRealmite, 2, LEGS).setDamageReduction(0.125D).setDescriptors(eliteRealmiteDesc).setUnlocalizedName("Eliterealmitelegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item eliteRealmiteBoots = new ItemEliteRealmiteArmor(1182, eliteRealmite, 3, BOOTS).setDamageReduction(0.125D).setDescriptors(eliteRealmiteDesc).setUnlocalizedName("Eliterealmiteboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item krakenHelmet = new ItemKrakenArmor(1183, kraken, 0, HEAD).setDamageReduction(0.75D).setDescriptors(krakenDesc).registerTextures("KrakenHelmet").setUnlocalizedName("Krakenhelmet").setCreativeTab(DivineRPG.Overworld);
    public static final Item krakenBody = new ItemKrakenArmor(1184, kraken, 1, BODY).setDamageReduction(0.75D).setDescriptors(krakenDesc).registerTextures("KrakenBody").setUnlocalizedName("Krakenbody").setCreativeTab(DivineRPG.Overworld);
    public static final Item krakenLegs = new ItemKrakenArmor(1185, kraken, 2, LEGS).setDamageReduction(0.75D).setDescriptors(krakenDesc).registerTextures("KrakenLegs").setUnlocalizedName("Krakenlegs").setCreativeTab(DivineRPG.Overworld);
    public static final Item krakenBoots = new ItemKrakenArmor(1186, kraken, 3, BOOTS).setDamageReduction(0.75D).setDescriptors(krakenDesc).registerTextures("KrakenBoots").setUnlocalizedName("Krakenboots").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineStick = new ItemDivineRPG(1187).registerTextures("DivineStick").setUnlocalizedName("DivineStick").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineWoodAxe = new ToolAxe(1188, divineWood).registerItemTexture("DivineWoodAxe").setUnlocalizedName("DivineWoodAxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineWoodPickaxe = new ToolPickaxe(1189, divineWood).registerItemTexture("DivineWoodPickaxe").setUnlocalizedName("DivineWoodPickaxe").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineWoodHoe = new ToolHoe(1190, divineWood).registerItemTexture("DivineWoodHoe").setUnlocalizedName("DivineWoodHoe").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineWoodShovel = new ToolShovel(1191, divineWood).registerItemTexture("DivineWoodShovel").setUnlocalizedName("DivineWoodShovel").setCreativeTab(DivineRPG.Overworld);
    public static final Item divineWoodSword = new ToolSword(1192, divineWood).registerItemTexture("DivineWoodSword").setUnlocalizedName("DivineWoodSword").setCreativeTab(DivineRPG.Overworld);

    public static void addNames()
    {
    	LanguageRegistry.addName(homeTeleporter, "Home Teleporter");
    	LanguageRegistry.addName(shadowStone, "Shadow Stone");
    	LanguageRegistry.addName(krakenScale, "Kraken Scale");
    	LanguageRegistry.addName(krakenSkin, "Kraken Skin");
    	LanguageRegistry.addName(callOfTheWatcher, "Call of the Watcher");
    	LanguageRegistry.addName(furyFire, "Fury Fire");
    	LanguageRegistry.addName(watchingEye, "Watching Eye");
    	LanguageRegistry.addName(mysteriousClock, "Mysterious Clock");
    	LanguageRegistry.addName(hordeHorn, "Horde Horn");
    	LanguageRegistry.addName(baseSpawnCrystal, "Base Spawn Crystal");
    	LanguageRegistry.addName(spawnSoulFiend, "Spawn Soul Fiend");
    	LanguageRegistry.addName(spawnVamacheron, "Spawn Vamacheron");
    	LanguageRegistry.addName(spawnTwilightDemon, "Spawn Twilight Demon");
    	LanguageRegistry.addName(spawnKarot, "Spawn Kar-OT");
    	LanguageRegistry.addName(spawnDensos, "Spawn Densos");
    	LanguageRegistry.addName(infernalFlame, "Infernal Flame");
    	LanguageRegistry.addName(legendaryEnderEye, "Legendary Ender Eye");
    	LanguageRegistry.addName(netheriteChunk, "Netherite Chunk");
    	LanguageRegistry.addName(shadowBar, "Shadow Bar");
    	LanguageRegistry.addName(infernoBow, "Inferno Bow");
    	LanguageRegistry.addName(arlemiteShickaxe, "Arlemite Shickaxe");
        LanguageRegistry.addName(rupeeShickaxe, "Rupee Shickaxe");
    	LanguageRegistry.addName(realmiteShovel, "Realmite Shovel");
        LanguageRegistry.addName(realmitePickaxe, "Realmite Pickaxe");
        LanguageRegistry.addName(realmiteAxe, "Realmite Axe");
        LanguageRegistry.addName(realmiteHoe, "Realmite Hoe");
    	LanguageRegistry.addName(arlemiteShovel, "Arlemite Shovel");
        LanguageRegistry.addName(arlemitePickaxe, "Arlemite Pickaxe");
        LanguageRegistry.addName(arlemiteAxe, "Arlemite Axe");
        LanguageRegistry.addName(arlemiteHoe, "Arlemite Hoe");
    	LanguageRegistry.addName(rupeeShovel, "Rupee Shovel");
        LanguageRegistry.addName(rupeePickaxe, "Rupee Pickaxe");
        LanguageRegistry.addName(rupeeAxe, "Rupee Axe");
        LanguageRegistry.addName(rupeeHoe, "Rupee Hoe");
    	LanguageRegistry.addName(bloodGem, "Blood Gem");
        LanguageRegistry.addName(divineStick, "Divine Wooden Stick");
        LanguageRegistry.addName(divineWoodAxe, "Divine Wooden Axe");
        LanguageRegistry.addName(divineWoodPickaxe, "Divine Wooden Pickaxe");
        LanguageRegistry.addName(divineWoodHoe, "Divine Wooden Hoe");
        LanguageRegistry.addName(divineWoodShovel, "Divine Wooden Shovel");
        LanguageRegistry.addName(divineWoodSword, "Divine Wooden Sword");
        LanguageRegistry.addName(infernoSword , "Inferno Sword");
        LanguageRegistry.addName(bedrockSword , "Bedrock Sword");
        LanguageRegistry.addName(sharkFin , "Shark Fin");
        LanguageRegistry.addName(whaleFin , "Whale Fin");
        LanguageRegistry.addName(purpleGlowBoneTree , "Purple Glow Bone Tree");
        LanguageRegistry.addName(pinkGlowBoneTree , "Pink Glow Bone Tree");
        LanguageRegistry.addName(enderShard , "Ender Shard");
        LanguageRegistry.addName(moltenShard , "Molten Shard");
        LanguageRegistry.addName(corruptedShard , "Corrupted Shard");
        LanguageRegistry.addName(jungleStone , "Jungle Stone");
        LanguageRegistry.addName(divineStone , "Divine Stone");
        LanguageRegistry.addName(iceStone , "Ice Stone");
        LanguageRegistry.addName(enderStone , "Ender Stone");
        LanguageRegistry.addName(moltenStone , "Molten Stone");
        LanguageRegistry.addName(corruptedStone , "Corrupted Stone");
        LanguageRegistry.addName(blueFireStone , "Blue Fire Stone");
        LanguageRegistry.addName(grimReaperHead , "Grim Reaper Head");
        LanguageRegistry.addName(grimReaperBody , "Grim Reaper Body");
        LanguageRegistry.addName(grimReaperLegs , "Grim Reaper Legs");
        LanguageRegistry.addName(grimReaperBoots , "Grim Reaper Boots");
        LanguageRegistry.addName(massivence , "Massivence");
        LanguageRegistry.addName(palavence , "Palavence");
        LanguageRegistry.addName(arlemiteSword , "Arlemite Stabber");
        LanguageRegistry.addName(rupeeSword , "Rupee Rapier");
        LanguageRegistry.addName(realmiteSword , "Realmite Sword");
        LanguageRegistry.addName(aquaticTrident , "Aquatic Trident");
        LanguageRegistry.addName(oceanKnife , "Ocean Knife");
        LanguageRegistry.addName(aquaton , "Aquaton");
        LanguageRegistry.addName(sharkSword , "Shark Sword");
        LanguageRegistry.addName(crabclawMaul , "Crabclaw Maul");
        LanguageRegistry.addName(deathBringer , "Death Bringer");
        LanguageRegistry.addName(corruptedMaul , "Corrupted Maul");
        LanguageRegistry.addName(moltenSword , "Molten Sword");
        //LanguageRegistry.addName(vileStorm , "Vile Storm");
        LanguageRegistry.addName(bowHeadAnchor , "Bowhead Anchor");
        LanguageRegistry.addName(crabAnchor , "Crab Anchor");
        LanguageRegistry.addName(bowheadCannon , "Bowhead Cannon");
        LanguageRegistry.addName(maelstrom , "Maelstrom");
        LanguageRegistry.addName(ghastCannon , "Ghast Cannon");
        LanguageRegistry.addName(corruptCannon , "Corrupt Cannon");
        LanguageRegistry.addName(serenadeHealth, "Serenade of Health");
        LanguageRegistry.addName(angelicHelmet, "Angelic Helmet");
        LanguageRegistry.addName(angelicBody, "Angelic Body");
        LanguageRegistry.addName(angelicLegs, "Angelic Legs");
        LanguageRegistry.addName(angelicBoots, "Angelic Boots");
        LanguageRegistry.addName(rupeeHelmet, "Rupee Helmet");
        LanguageRegistry.addName(rupeeBody, "Rupee Body");
        LanguageRegistry.addName(rupeeLegs, "Rupee Legs");
        LanguageRegistry.addName(rupeeBoots, "Rupee Boots");
        LanguageRegistry.addName(realmiteHelmet, "Realmite Helmet");
        LanguageRegistry.addName(realmiteBody, "Realmite Body");
        LanguageRegistry.addName(realmiteLegs, "Realmite Legs");
        LanguageRegistry.addName(realmiteBoots, "Realmite Boots");
        LanguageRegistry.addName(eliteRealmiteHelmet, "Elite Realmite Helmet");
        LanguageRegistry.addName(eliteRealmiteBody, "Elite Realmite Body");
        LanguageRegistry.addName(eliteRealmiteLegs, "Elite Realmite Legs");
        LanguageRegistry.addName(eliteRealmiteBoots, "Elite Realmite Boots");
        LanguageRegistry.addName(arlemiteHelmet, "Arlemite Helmet");
        LanguageRegistry.addName(arlemiteBody, "Arlemite Body");
        LanguageRegistry.addName(arlemiteLegs, "Arlemite Legs");
        LanguageRegistry.addName(arlemiteBoots, "Arlemite Boots");
        LanguageRegistry.addName(aquaticHelmet, "Aquatic Helmet");
        LanguageRegistry.addName(aquaticBody, "Aquatic Body");
        LanguageRegistry.addName(aquaticLegs, "Aquatic Legs");
        LanguageRegistry.addName(aquaticBoots, "Aquatic Boots");
        LanguageRegistry.addName(shadowHelmet, "Shadow Helmet");
        LanguageRegistry.addName(serenadeOfDeath , "Serenade Of Death");
        LanguageRegistry.addName(shadowBody, "Shadow Body");
        LanguageRegistry.addName(shadowLegs, "Shadow Legs");
        LanguageRegistry.addName(shadowBoots, "Shadow Boots");
        LanguageRegistry.addName(bedrockMaul, "Bedrock Maul");
        LanguageRegistry.addName(soundOfMusic, "Sound of Music");
        LanguageRegistry.addName(jungleShard, "Jungle Shards");
        //LanguageRegistry.addName(shuriken, "Shuriken");
        LanguageRegistry.addName(serenadeStriker, "Serenade of Strikes");
        LanguageRegistry.addName(slimeSword, "Slime Sword");
        LanguageRegistry.addName(shadowBow, "Shadow Bow");

        LanguageRegistry.addName(arlemiteIngot, "Arlemite Ingot");
        LanguageRegistry.addName(realmiteIngot, "Realmite Ingot");
        LanguageRegistry.addName(netheriteIngot, "Netherite Bar");
        LanguageRegistry.addName(hellStoneIngot, "HellStone Ingot");
        LanguageRegistry.addName(serenadeOfLife, "Serenade Of Growth");

        LanguageRegistry.addName(crabClawCannon, "Crabclaw Cannon");
        LanguageRegistry.addName(frostCannon, "Frost Cannon");
        LanguageRegistry.addName(frostSword, "Frost Sword");
        LanguageRegistry.addName(divineSword, "Divine Sword");
        LanguageRegistry.addName(sandSlash, "Sandslash");
        LanguageRegistry.addName(iceShard, "Corrupted Shards");
        LanguageRegistry.addName(iceShard, "Frozen Shards");
        LanguageRegistry.addName(divineShard, "Divine Shards");
        LanguageRegistry.addName(enderSword, "Ender Sword");
        LanguageRegistry.addName(enderSwordBlue, "Blue Ender Sword");
        LanguageRegistry.addName(enderSwordDark, "Dark Ender Sword");
        LanguageRegistry.addName(enderSwordGreen, "Green Ender Sword");
        LanguageRegistry.addName(enderSwordRed, "Red Ender Sword");
        LanguageRegistry.addName(enderSwordYellow, "Yellow Ender Sword");

        LanguageRegistry.addName(twilightClock, "Twilight Clock");

        LanguageRegistry.addName(krakenHelmet, "Kraken Helmet");
        LanguageRegistry.addName(krakenBody, "Kraken Body");
        LanguageRegistry.addName(krakenLegs, "Kraken Legs");
        LanguageRegistry.addName(krakenBoots, "Kraken Boots");
        LanguageRegistry.addName(enderSword, "Ender Sword");
        LanguageRegistry.addName(bluefirebow, "Bluefire Bow");
        LanguageRegistry.addName(rupeeIngot, "Rupee Ingot");
        LanguageRegistry.addName(tomato, "Tomato");
        LanguageRegistry.addName(tomatoSeeds, "Tomato Seeds");
        LanguageRegistry.addName(purpleBlaze, "Purple Blaze");
        LanguageRegistry.addName(jackOManBoots, "Jack-O-Man Boots");
        LanguageRegistry.addName(jackOManLegs, "Jack-O-Man Legs");
        LanguageRegistry.addName(jackOManBody, "Jack-O-Man Body");
        LanguageRegistry.addName(jackOManHead, "Jack-O-Man Head");
        LanguageRegistry.addName(scythe, "Scythe");
        LanguageRegistry.addName(sharkAnchor, "Shark Anchor");
        LanguageRegistry.addName(healingStone, "Healing Stone");
    }
}
