package net.divinerpg.helper.block;

import net.divinerpg.DivineRPG;
import net.divinerpg.block.BlockDivineSpawner;
import net.divinerpg.block.ModBlock;
import net.divinerpg.block.ModDirt;
import net.divinerpg.helper.config.BlockConfigHelper;
import net.divinerpg.vethea.block.BlockAcid;
import net.divinerpg.vethea.block.BlockBacterialAcid;
import net.divinerpg.vethea.block.BlockBarredDoor;
import net.divinerpg.vethea.block.BlockDreamLamp;
import net.divinerpg.vethea.block.BlockDreamgrass;
import net.divinerpg.vethea.block.BlockDreamwood;
import net.divinerpg.vethea.block.BlockDreamwoodLeaves;
import net.divinerpg.vethea.block.BlockHelioticBeam;
import net.divinerpg.vethea.block.BlockInfusionTable;
import net.divinerpg.vethea.block.BlockKarosCannon;
import net.divinerpg.vethea.block.BlockKarosHeatTileGreen;
import net.divinerpg.vethea.block.BlockKarosHeatTileRed;
import net.divinerpg.vethea.block.BlockLunicAcid;
import net.divinerpg.vethea.block.BlockPurpleFire;
import net.divinerpg.vethea.block.BlockShimmer;
import net.divinerpg.vethea.block.BlockSmoothGlass;
import net.divinerpg.vethea.block.BlockVethea;
import net.divinerpg.vethea.block.BlockVetheaPlant;
import net.divinerpg.vethea.block.BlockVetheaPortal;
import net.divinerpg.vethea.block.BlockWeedwoodVine;
import net.divinerpg.vethea.block.BlockWreckAltar;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class VetheaBlockHelper {

	public static BlockConfigHelper x;

    // SPAWNERS
    public static final Block dreamwreckerSpawner = new BlockDivineSpawner(x.dreamwreckerSpawnerID, "Dreamwrecker").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Vethea);
    public static final Block vermenousSpawner = new BlockDivineSpawner(x.vermenousSpawnerID, "Vermenous").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Vethea);
    public static final Block twinsSpawner = new BlockDivineSpawner(x.twinsSpawnerID, "Twins").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Vethea);
    public static final Block biphronSpawner = new BlockDivineSpawner(x.biphronSpawnerID, "Biphron").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Vethea);
    public static final Block gorgosionSpawner = new BlockDivineSpawner(x.gorgosionSpawnerID, "Gorgosion").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Vethea);
    
    
    public static final Block wreckAltar = new BlockWreckAltar(x.wreckAltarID).registerTexture("WreckAltar").setCreativeTab(DivineRPG.Vethea);
    public static final Block quadroticAltar = new ModBlock(x.quadroticAltarID).registerTexture("QuadroticAltar").setCreativeTab(DivineRPG.Vethea);
    public static final Block karosAltar = new ModBlock(x.karosAltarID).registerTexture("KarosAltar").setCreativeTab(DivineRPG.Vethea);
    public static final Block raglokAltar = new ModBlock(x.raglokAltarID).registerTexture("RaglokAltar").setCreativeTab(DivineRPG.Vethea);
    public static final BlockVetheaPortal vetheaPortal = (BlockVetheaPortal)new BlockVetheaPortal(x.vetheaPortalID).registerTexture("VetheaPortal").setUnlocalizedName("VetheaPortal").setBlockUnbreakable();
    public static final Block lunicAltar = new ModBlock(x.lunicAltarID).registerTexture("LunicAltar").setUnlocalizedName("Lunic").setCreativeTab(DivineRPG.Vethea);

    public static final Block dreamstone = new BlockVethea(x.dreamstoneID, Material.rock).setUnlocalizedName("dreamstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamdirt = new ModDirt(x.DreamDirtID).registerTexture("DreamGrass_Bottom").setUnlocalizedName("dreamdirt").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamgrass = new BlockDreamgrass(x.DreamGrassID).setUnlocalizedName("dreamgrass").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamwood = new BlockDreamwood(x.dreamwoodID, "Dream").setUnlocalizedName("dreamwood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamwoodLeaves = new BlockDreamwoodLeaves(x.dreamwoodLeavesID, "DreamWood").setUnlocalizedName("dreamwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreambricks = new BlockVethea(x.dreambricksID, Material.rock).registerTexture("DreamBricks1").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block lunastone = new BlockVethea(x.lunastoneID, Material.rock).registerTexture("").setBlockUnbreakable().setUnlocalizedName("lunastone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block lunabricks = new BlockVethea(x.lunabricksID, Material.rock).registerTexture("LunaBrick").setBlockUnbreakable().setUnlocalizedName("lunabricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block metalCaging = new BlockVethea(x.metalCagingID, Material.rock).registerTexture("MetalCaging").setUnlocalizedName("metalCaging").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamlampOn = new BlockDreamLamp(x.dreamlampOnID, 30, Material.glass, true).registerTexture("DreamLamp_On").setBlockUnbreakable().setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setLightValue(1.0F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamlamp = new BlockDreamLamp(x.dreamlampID, 31, Material.glass, false).registerTexture("DreamLamp_Off").setBlockUnbreakable().setUnlocalizedName("dreamlamp").setHardness(1F).setStepSound(Block.soundGlassFootstep).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block weedwoodVine = new BlockWeedwoodVine(x.weedwoodVineID, 41).registerTexture("WeedWoodVine").setUnlocalizedName("weedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block blossomingWeedwoodVine = new BlockWeedwoodVine(x.blossomingWeedwoodVineID, 42).registerTexture("WeedWoodVineBlossomed").setUnlocalizedName("blossomingWeedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block cryptWall = new BlockVethea(x.cryptWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("cryptWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block smoothGlass = new BlockSmoothGlass(x.smoothGlassID, 44, Material.glass).registerTexture("SmoothGlass").setStepSound(Block.soundGlassFootstep).setUnlocalizedName("smoothGlass").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block villageLamp = new BlockVethea(x.villageLampID, Material.glass).registerTexture("VillageLamp").setUnlocalizedName("villageLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block cellLamp = new BlockVethea(x.cellLampID, Material.glass).registerTexture("CellLamp").setUnlocalizedName("cellLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block barredDoor = new BlockBarredDoor(x.barredDoorID, Material.wood).setUnlocalizedName("barredDoor").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block firecrystal = new BlockVethea(x.firecrystalID, Material.glass).registerTexture("FireCrystal").setLightValue(0.7F).setUnlocalizedName("firecrystal").setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block firelight = new BlockVethea(x.firelightID, Material.glass).registerTexture("FireLight").setUnlocalizedName("firelight").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setResistance(1.0F).setCreativeTab(DivineRPG.Vethea);
    public static final Block hyrewood = new BlockDreamwood(x.hyrewoodID, "Hyre").setUnlocalizedName("hyrewood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block mintwoodLeaves = new BlockDreamwoodLeaves(x.mintwoodLeavesID, "MintWood").setUnlocalizedName("mintwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block firewall = new BlockVethea(x.firewallID, Material.rock).registerTexture("FireWall").setUnlocalizedName("firewall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block karosHeatTileGreen = new BlockKarosHeatTileGreen(x.karosHeatTileGreenID, false).registerTexture("KarosHeatTile1").setBlockUnbreakable().setUnlocalizedName("karosHeatTileGreen").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block karosHeatTileRed = new BlockKarosHeatTileRed(x.karosHeatTileRedID, true).registerTexture("KarosHeatTile2").setBlockUnbreakable().setUnlocalizedName("karosHeatTileRed").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block firewood = new BlockDreamwood(x.firewoodID, "Fire").setUnlocalizedName("firewood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block bacterialAcid = new BlockBacterialAcid(x.bacterialAcidID).registerTexture("VetheaPortal").setUnlocalizedName("bacterialAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block blockAcid = new BlockAcid(x.blockAcidID).registerTexture("VetheaPortal").setUnlocalizedName("blockAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block everstone = new BlockVethea(x.everstoneID, Material.rock).registerTexture("EverStone").setBlockUnbreakable().setUnlocalizedName("everstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block lunicAcid = new BlockLunicAcid(x.lunicAcidID, 141).registerTexture("VetheaPortal").setUnlocalizedName("lunicAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block firewoodLeaves = new BlockDreamwoodLeaves(x.firewoodLeavesID, "FireWood").setUnlocalizedName("firewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block hyrewoodLeaves = new BlockDreamwoodLeaves(x.hyrewoodLeavesID, "HyreWood").setUnlocalizedName("hyrewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block gemtopGreen = new BlockVetheaPlant(x.gemtopGreenID).setUnlocalizedName("gemtopGreen").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block gemtopPurple = new BlockVetheaPlant(x.gemtopPurpleID).setUnlocalizedName("gemtopPurple").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block yellowDulah = new BlockVetheaPlant(x.yellowDulahID).setUnlocalizedName("yellowDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block greenDulah = new BlockVetheaPlant(x.greenDulahID).setUnlocalizedName("greenDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block mintwood = new BlockDreamwood(x.mintwoodID, "Mint").setUnlocalizedName("mint").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block lightFirewoodLeaves = new BlockDreamwoodLeaves(x.lightFirewoodLeavesID, "FireWood").setUnlocalizedName("lightFirewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block cracklespike = new BlockVetheaPlant(x.cracklespikeID).registerTexture("SpikeBlock").setUnlocalizedName("cracklespike").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block fernite = new BlockVetheaPlant(x.ferniteID).setUnlocalizedName("fernite").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block bulatobe = new BlockVetheaPlant(x.bulatobeID).setUnlocalizedName("bulatobe").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block shineGrass = new BlockVetheaPlant(x.shineGrassID).setUnlocalizedName("shineGrass").setLightValue(0.4F).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block shimmer = new BlockShimmer(x.shimmerID).setLightValue(0.4F).setUnlocalizedName("shimmer").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block hiveWall = new BlockVethea(x.hiveWallID, Material.glass).registerTexture("HiveWalls").setLightValue(0.533F).setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreamglow = new BlockShimmer(x.dreamglowID).setLightValue(0.4F).setUnlocalizedName("dreamglow").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Vethea);
    public static final Block hyrewoodVine = new BlockWeedwoodVine(x.hyrewoodVineID, 175).registerTexture("WeedWoodVine").setUnlocalizedName("hyrewoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block dreambricks2 = new BlockVethea(x.dreambricks2ID, Material.rock).registerTexture("DreamBricks2").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block chamberWall = new BlockVethea(x.chamberWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("chamberWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block chamberWall1 = new BlockVethea(x.chamberWall1ID, Material.rock).registerTexture("ChamberWall2").setBlockUnbreakable().setUnlocalizedName("chamberWall1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block chamberWall2 = new BlockVethea(x.chamberWall2ID, Material.rock).registerTexture("ChamberWall3").setBlockUnbreakable().setUnlocalizedName("chamberWall2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block whiteEverstone = new BlockVethea(x.whiteEverstoneID, Material.rock).registerTexture("EverStone").setBlockUnbreakable().setUnlocalizedName("whiteEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block darkEverstone = new BlockVethea(x.darkEverstoneID, Material.rock).registerTexture("EverStone").setBlockUnbreakable().setUnlocalizedName("darkEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block infusionTable = new BlockInfusionTable(x.infusionTableID).registerTexture("InfusionTable_Side", "InfusionTable_Top", "InfusionTable_Side").setBlockUnbreakable().setUnlocalizedName("infusionTable").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineRPG.Vethea);
    public static final Block hungerstone1 = new BlockVethea(x.hungerstone1ID, Material.rock).registerTexture("HungerStone1").setUnlocalizedName("hungerstone1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block hungerstone2 = new BlockVethea(x.hungerstone2ID, Material.rock).registerTexture("HungerStone2").setUnlocalizedName("hungerstone2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block cryptFloor = new BlockVethea(x.cryptFloorID, Material.rock).registerTexture("CryptFloor").setBlockUnbreakable().setUnlocalizedName("cryptFloor").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block hallWall = new BlockVethea(x.hallWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("hallWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block karosBricks = new BlockVethea(x.karosBricksID, Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block karosBricks2 = new BlockVethea(x.karosBricks2ID, Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final BlockHelioticBeam helioticBeam = (BlockHelioticBeam) new BlockHelioticBeam(x.helioticBeamID).registerTexture("HelioticBeam_Side", "HelioticBeam_Top", "HelioticBeam_Top").setUnlocalizedName("helioticBeam").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final BlockKarosCannon karosCannon = (BlockKarosCannon) new BlockKarosCannon(x.karosCannonID, Material.rock).registerTexture("HelioticBeam_Side", "HelioticBeam_Top", "HelioticBeam_Top").setBlockUnbreakable().setUnlocalizedName("karosCannon").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Vethea);
    public static final Block purpleFire = new BlockPurpleFire(x.purpleFireID).setUnlocalizedName("purpleFire");
    

    public static void addNames()
    {
    	GameRegistry.registerBlock(purpleFire, "Purple Fire");
        GameRegistry.registerBlock(vetheaPortal, "vetheaPortal");
        GameRegistry.registerBlock(everstone, "everstone");
        GameRegistry.registerBlock(whiteEverstone, "whiteEverstone");
        GameRegistry.registerBlock(darkEverstone, "darkEverstone");
        GameRegistry.registerBlock(dreamgrass, "dreamgrass");
        GameRegistry.registerBlock(dreamdirt, "dreamdirt");
        GameRegistry.registerBlock(dreamlampOn, "dreamlampOn");
        GameRegistry.registerBlock(dreamlamp, "dreamlamp");
        GameRegistry.registerBlock(firecrystal, "firecrystal");
        GameRegistry.registerBlock(hiveWall, "hiveWall");
        GameRegistry.registerBlock(hyrewood, "hyrewood");
        GameRegistry.registerBlock(firewood, "firewood");
        GameRegistry.registerBlock(mintwood, "mintwood");
        GameRegistry.registerBlock(dreamwood, "dreamwood");
        GameRegistry.registerBlock(hyrewoodLeaves, "hyrewoodLeaves");
        GameRegistry.registerBlock(firewoodLeaves, "firewoodLeaves");
        GameRegistry.registerBlock(mintwoodLeaves, "mintwoodLeaves");
        GameRegistry.registerBlock(dreamwoodLeaves, "dreamwoodLeaves");
        GameRegistry.registerBlock(infusionTable, "infusionTable");
        GameRegistry.registerBlock(purpleFire, "PurpleFire");
        GameRegistry.registerBlock(karosCannon, "karosCannon");
        GameRegistry.registerBlock(dreambricks, "dreambricks");
        GameRegistry.registerBlock(dreambricks2, "dreambricks2");
        GameRegistry.registerBlock(lunastone, "lunastone");
        GameRegistry.registerBlock(lunabricks, "lunabricks");
        GameRegistry.registerBlock(metalCaging, "metalCaging");
        GameRegistry.registerBlock(cryptWall, "cryptWall");
        GameRegistry.registerBlock(smoothGlass, "smoothGlass");
        GameRegistry.registerBlock(villageLamp, "villageLamp");
        GameRegistry.registerBlock(cellLamp, "cellLamp");
        GameRegistry.registerBlock(barredDoor, "barredDoor");
        GameRegistry.registerBlock(firelight, "firelight");
        GameRegistry.registerBlock(firewall, "firewall");
        GameRegistry.registerBlock(karosHeatTileRed, "karosHeatTileRed");
        GameRegistry.registerBlock(karosHeatTileGreen, "karosHeatTileGreen");
        GameRegistry.registerBlock(helioticBeam, "helioticBeam");
        GameRegistry.registerBlock(cryptFloor, "cryptFloor");
        GameRegistry.registerBlock(chamberWall, "chamberWall");
        GameRegistry.registerBlock(chamberWall1, "chamberWall1");
        GameRegistry.registerBlock(chamberWall2, "chamberWall2");
        GameRegistry.registerBlock(wreckAltar, "wreckAltar");
        GameRegistry.registerBlock(raglokAltar, "raglokAltar");
        GameRegistry.registerBlock(karosAltar, "karosAltar");
        GameRegistry.registerBlock(lunicAltar, "lunicAltar");
        GameRegistry.registerBlock(quadroticAltar, "quadroticAltar"); 
        LanguageRegistry.addName(dreamstone, "Dreamstone");
        LanguageRegistry.addName(dreamgrass, "Dream Grass");
        LanguageRegistry.addName(dreamdirt, "Dream Dirt");
        LanguageRegistry.addName(dreamwood, "Dreamwod");
        LanguageRegistry.addName(dreamwoodLeaves, "Dreamwood Leaves");
        LanguageRegistry.addName(dreambricks, "Dreambricks");
        LanguageRegistry.addName(dreambricks2, "Dreambricks");
        LanguageRegistry.addName(lunastone, "Lunastone");
        LanguageRegistry.addName(metalCaging, "Metal Caging");
        LanguageRegistry.addName(weedwoodVine, "Weedwood Vines");
        LanguageRegistry.addName(blossomingWeedwoodVine, "Blossoming Weedwood Vines");
        LanguageRegistry.addName(cryptWall, "Crypt Wall");
        LanguageRegistry.addName(smoothGlass, "Smooth Glass");
        LanguageRegistry.addName(villageLamp, "Altar Lamps");
        LanguageRegistry.addName(infusionTable, "Infusion Table");
        LanguageRegistry.addName(cellLamp, "Cell Lamp");
        LanguageRegistry.addName(barredDoor, "Barred Door");
        LanguageRegistry.addName(firecrystal, "Firecrystal");
        LanguageRegistry.addName(firelight, "Firelight");
        LanguageRegistry.addName(hyrewood, "Hyrewood");
        LanguageRegistry.addName(mintwoodLeaves, "Mintwood Leaves");
        LanguageRegistry.addName(firewall, "Firewall");
        LanguageRegistry.addName(karosHeatTileGreen, "Karos Heat Tile");
        LanguageRegistry.addName(karosHeatTileRed, "Karos Heat Tile");
        LanguageRegistry.addName(karosCannon, "Karos Cannon");
        LanguageRegistry.addName(helioticBeam, "Heliotic Beam");
        LanguageRegistry.addName(cryptFloor, "Crypt Floor");
        LanguageRegistry.addName(firewood, "Firewood");
        LanguageRegistry.addName(chamberWall, "Chamber Wall");
        LanguageRegistry.addName(chamberWall1, "Chamber Wall");
        LanguageRegistry.addName(chamberWall2, "Chamber Wall");
        LanguageRegistry.addName(karosBricks, "Karos Bricks");
        LanguageRegistry.addName(karosBricks2, "Karos Bricks");
        LanguageRegistry.addName(bacterialAcid, "Bacterial Acid");
        LanguageRegistry.addName(hungerstone1, "Hungerstone");
        LanguageRegistry.addName(hungerstone2, "Hungerstone");
        LanguageRegistry.addName(blockAcid, "Acid");
        LanguageRegistry.addName(hallWall, "Hall Wall");
        LanguageRegistry.addName(wreckAltar, "Wreck Altar");
        LanguageRegistry.addName(raglokAltar, "Raglok Altar");
        LanguageRegistry.addName(karosAltar, "Karos Altar");
        LanguageRegistry.addName(lunicAltar, "Lunic Altar");
        LanguageRegistry.addName(quadroticAltar, "Quadrotic Altar");
        LanguageRegistry.addName(hiveWall, "Hive Walls");
        LanguageRegistry.addName(darkEverstone, "Dark Everstone");
        LanguageRegistry.addName(whiteEverstone, "White Everstone");
        LanguageRegistry.addName(everstone, "Everstone");
        LanguageRegistry.addName(lunicAcid, "Lunic Acid");
        LanguageRegistry.addName(firewoodLeaves, "Firewood Leaves");
        LanguageRegistry.addName(hyrewoodLeaves, "Hyrewood Leaves");
        LanguageRegistry.addName(gemtopGreen, "Green Gemtops");
        LanguageRegistry.addName(gemtopPurple, "Purple Gemtops");
        LanguageRegistry.addName(yellowDulah, "Yellow Dulahs");
        LanguageRegistry.addName(greenDulah, "Green Dulahs");
        LanguageRegistry.addName(mintwood, "Mintwood");
        LanguageRegistry.addName(lightFirewoodLeaves, "Light Firewood Leaves");
        LanguageRegistry.addName(cracklespike, "Crackle Spikes");
        LanguageRegistry.addName(fernite, "Fernites");
        LanguageRegistry.addName(bulatobe, "Bulbatobes");
        LanguageRegistry.addName(shineGrass, "Shine Grass");
        LanguageRegistry.addName(shimmer, "Shimmers");
        LanguageRegistry.addName(dreamglow, "Dream Glows");
        LanguageRegistry.addName(hyrewoodVine, "Hyrewood Vines");
    }
}
