package net.divinerpg.helper.config;

import java.io.File;

import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

public class BlockConfigHelper{
	
	public static int IceGrassID = 180;
	public static int IceDirtID = 181; 
	public static int IceStoneID = 182;
	public static int TwilightStoneID = 183;
	public static int DraviteGrassID;
	public static int DraviteDirtID;
	public static int AzuriteGrassID;
	public static int AzuriteDirtID;
	public static int UviteGrassID;
	public static int UviteDirtID;
	public static int MythrilGrassID;
	public static int MythrilDirtID;
	public static int AugiteGrassID;
	public static int AugiteDirtID;
	public static int DreamGrassID = 194;
	public static int DreamDirtID = 195;
	public static int ArcanaGrassID = 196;
	public static int ArcanaDirtID = 197;
	
	public static int RupeeOreID;
	public static int ArlemiteOreID;
	public static int RealmiteOreID;
	public static int NetheriteOreID;
	public static int BloodGemOreID;
	public static int BlueFireID;
	
	public static int DivineStoneID;
	public static int RupeeBlockID;
	public static int ArlemiteBlockID;
	public static int RealmiteBlockID;
	public static int NetheriteBlockID;
	public static int ObsidianBlockID;
	public static int DivineLogID;
	public static int DivinePlankID;
	public static int DivineLeavesID;
	public static int DivineMossyID;
	public static int Spawner1ID;
	
	public static int IceikaPortalID; 
	public static int IceLogID;
	public static int IceLeavesID;
	public static int CoalStoneID;
	public static int WorkLampID;
	public static int SnowBrickID;
	public static int IceBrickID;
	public static int WorkBookcaseID;
	public static int FrostGlassID;
	public static int CoalstoneFurnaceID;
	public static int FrostChestID;
	public static int FrostStoneID;
	public static int RolumSpawnerID; 
	public static int GlacideSpawnerID;
	public static int WorkCarpetID; 
	public static int CoalstoneFurnaceOnID;
	
	
	public static int DravitePortalID;
	public static int AzuritePortalID;
	public static int UvitePortalID;
	public static int MythrilPortalID;
	public static int AugitePortalID;
	public static int DraviteBlockID;
	public static int AzuriteBlockID;
	public static int UviteBlockID;
	public static int MythrilBlockID;
	public static int AugiteBlockID;	
	public static int DraviteOreID;
	public static int AzuriteOreID;
	public static int UviteOreID;
	public static int MythrilOreID;
	public static int AugiteOreID;
	public static int DraviteLogID;
	public static int AzuriteLogID;
	public static int UviteLogID;
	public static int MythrilLogID;
	public static int AugiteLogID;
	public static int DraviteLeavesID;
	public static int AzuriteLeavesID;
	public static int UviteLeavesID;
	public static int MythrilLeavesID;
	public static int AugiteLeavesID;
	public static int AzuriteVineID;
	
	public static int ArcanaPortalID;
	public static int MoltenFurnaceID;
	public static int MoltenFurnaceOnID;
	public static int MoonlightFurnaceID;
	public static int MoonlightFurnaceOnID;
	public static int OceanFireFurnaceID;
	public static int OceanFireFurnaceOnID;
	public static int WhiteFireFurnaceID;
	public static int WhiteFireFurnaceOnID;
	public static int GreenLightFurnaceID;
	public static int GreenLightFurnaceOnID;
	public static int DemonFurnaceID;
	public static int DemonFurnaceOnID;
	public static int ArcaniumOreID;
	public static int StarBridgeOnID;
	public static int StarBridgeID;
	public static int ArcanaPortalFrameID;
	public static int ExtractorID;
	public static int HeatTrapOnID;
	public static int HeatTrapID;
	public static int AncientBricksID;
	public static int DegradedBricksID;
	public static int ArcaniumMetalID;
	public static int ArcaniumPowerID;
	public static int AncientStoneID;
	public static int SoulStoneID;
	public static int DungeonLampID;
	public static int AncientTileID;
	public static int SoulSludgeID;
	public static int ParasectaAltarID;
	public static int DramixAltarID;
	public static int RoamerSpawnerID;
	public static int DeathcryxSpawnerID;
	public static int DeathHoundSpawnerID;
	public static int RazorbackSpawnerID;
	public static int LivingStatueSpawnerID;
	public static int DungeonPrisonerSpawnerID;
	public static int ArcaniteTubesID;
	public static int ArcaniteRailsID;
	public static int OreDoor1BlockID;
	public static int OreDoor2BlockID;
	public static int OreDoor3BlockID;
	public static int OreDoor4BlockID;
	
	public static int vetheaPortalID;
    public static int dreamstoneID;
    public static int dreamgrassID;
    public static int dreamdirtID;
    public static int dreamwoodID;
    public static int dreamwoodLeavesID;
    public static int dreambricksID;
    public static int dreambricks2ID;
    public static int lunastoneID;
    public static int lunabricksID;
    public static int metalCagingID;
    public static int dreamlampID;
    public static int dreamlampOnID;
    public static int weedwoodVineID;
    public static int blossomingWeedwoodVineID;
    public static int cryptWallID;
    public static int smoothGlassID;
    public static int villageLampID;
    public static int infusionTableID;
    public static int cellLampID;
    public static int barredDoorID;
    public static int firecrystalID;
    public static int firelightID;
    public static int hyrewoodID;
    public static int mintwoodLeavesID;
    public static int firewallID;
    public static int karosHeatTileRedID;
    public static int karosHeatTileGreenID;
    public static int karosCannonID;
    public static int helioticBeamID;
    public static int cryptFloorID;
    public static int firewoodID;
    public static int bacterialAcidID;
    public static int blockAcidID;
    public static int hallWallID;
    public static int wreckAltarID;
    public static int raglokAltarID;
    public static int karosAltarID;
    public static int lunicAltarID;
    public static int hiveWallID;
    public static int quadroticAltarID;
    public static int everstoneID;
    public static int lunicAcidID;
    public static int firewoodLeavesID;
    public static int hyrewoodLeavesID;
    public static int gemtopGreenID;
    public static int gemtopPurpleID;
    public static int greenDulahID;
    public static int yellowDulahID;
    public static int mintwoodID;
    public static int lightFirewoodLeavesID;
    public static int cracklespikeID;
    public static int ferniteID;
    public static int bulatobeID;
    public static int shineGrassID;
    public static int shimmerID;
    public static int dreamglowID;
    public static int hyrewoodVineID;
    public static int chamberWallID;
    public static int chamberWall1ID;
    public static int chamberWall2ID;
    public static int darkEverstoneID;
    public static int whiteEverstoneID;
    public static int karosBricksID;
    public static int karosBricks2ID;
    public static int hungerstone1ID;
    public static int hungerstone2ID;
    public static int biphronSpawnerID;
    public static int gorgosionSpawnerID;
    public static int duoSpawnerID;
    public static int twinsSpawnerID;
    public static int vermenousSpawnerID;
    public static int dreamwreckerSpawnerID;
    public static int lorgaSpawnerID;
    public static int purpleFireID;
	
	
    public static void initConfig(FMLPreInitializationEvent event) {
		File file = new File(event.getModConfigurationDirectory(), "DivineRPGBlocks.cfg");
		Configuration config = new Configuration(file);
		
		config.load();
		
		DraviteGrassID = config.getTerrainBlock("Dravite", "DraviteGrass", 160, "Dravite Generation").getInt();
		DraviteDirtID = config.getTerrainBlock("Dravite", "DraviteDirt", 161, "Dravite Generation").getInt();
		AzuriteGrassID = config.getTerrainBlock("Azurite", "AzuriteGrass", 162, "Azurite Generation").getInt();
		AzuriteDirtID = config.getTerrainBlock("Azurite", "AzuriteDirt", 163, "Azurite Generation").getInt();
		UviteGrassID = config.getTerrainBlock("Uvite", "UviteGrass", 164, "Uvite Generation").getInt();
		UviteDirtID = config.getTerrainBlock("Uvite", "UviteDirt", 165, "Uvite Generation").getInt();
		MythrilGrassID = config.getTerrainBlock("Mythril", "MythrilGrass", 166, "Mythril Generation").getInt();
		MythrilDirtID = config.getTerrainBlock("Mythril", "MythrilDirt", 167, "Mythril Generation").getInt();
		AugiteGrassID = config.getTerrainBlock("Augite", "AugiteGrass", 168, "Augite Generation").getInt();
		AugiteDirtID = config.getTerrainBlock("Augite", "AugiteDirt", 169, "Augite Generation").getInt();
		
		RupeeOreID = config.getBlock("RupeeOre", 2000).getInt();
		ArlemiteOreID = config.getBlock("ArlemiteOre", 2001).getInt();
		RealmiteOreID = config.getBlock("RealmiteOre", 2002).getInt();
		NetheriteOreID = config.getBlock("NetheriteOre", 2003).getInt();
		BloodGemOreID = config.getBlock("BloodGemOre", 2004).getInt();
		BlueFireID = config.getBlock("BlueFire", 2005).getInt();
		DivineStoneID = config.getBlock("DivineStone", 2006).getInt();
		RupeeBlockID = config.getBlock("RupeeBlock", 2007).getInt();
		ArlemiteBlockID = config.getBlock("ArlemiteBlock", 2008).getInt();
		RealmiteBlockID = config.getBlock("RealmiteBlock", 2009).getInt();
		NetheriteBlockID = config.getBlock("NetheriteBlock", 2010).getInt();
		ObsidianBlockID = config.getBlock("ObsidianBlock", 2011).getInt();
		DivineLogID = config.getBlock("DivineLog", 2012).getInt();
		DivinePlankID = config.getBlock("DivinePlank", 2013).getInt();
		DivineLeavesID = config.getBlock("DivineLeaves", 2014).getInt();
		DivineMossyID = config.getBlock("DivineMossy", 2015).getInt();
		Spawner1ID = config.getBlock("Spawner1", 2016).getInt();
		
		IceikaPortalID = config.getBlock("IceikaPortal", 1250).getInt();
		IceLogID = config.getBlock("IceLog", 1251).getInt();
		IceLeavesID = config.getBlock("IceLeaves", 1252).getInt();
		CoalStoneID = config.getBlock("Coalstone", 1253).getInt();
		WorkLampID = config.getBlock("WorkLamp", 2254).getInt();
		SnowBrickID = config.getBlock("SnowBrick", 2255).getInt();
		IceBrickID = config.getBlock("IceBrick", 2256).getInt();
		WorkBookcaseID = config.getBlock("WorkBookcase", 2257).getInt();
		FrostGlassID = config.getBlock("FrostGlass", 2258).getInt();
		CoalstoneFurnaceID = config.getBlock("CoalstoneFurnaceIdle", 2259).getInt();
		FrostChestID = config.getBlock("FrostChest", 2260).getInt();
		FrostStoneID = config.getBlock("FrostStone", 2261).getInt();
		RolumSpawnerID = config.getBlock("RolumSpawner", 2262).getInt();
		GlacideSpawnerID = config.getBlock("GlacideSpawner", 2263).getInt();
		WorkCarpetID = config.getBlock("WorkCarpet", 2264).getInt();
		CoalstoneFurnaceOnID = config.getBlock("CoalstoneFurnaceOn", 2265).getInt();

		DravitePortalID = config.getBlock("DravitePortal", 2300).getInt();
		AzuritePortalID = config.getBlock("AzuritePortal", 2301).getInt();
		UvitePortalID = config.getBlock("UvitePortal", 2302).getInt();
		MythrilPortalID = config.getBlock("MythrilPortal", 2303).getInt();
		AugitePortalID = config.getBlock("AugitePortal", 2304).getInt();

		DraviteBlockID = config.getBlock("DraviteBlock", 2305).getInt();
		AzuriteBlockID = config.getBlock("AzuriteBlock", 2306).getInt();
		UviteBlockID = config.getBlock("UviteBlock", 2307).getInt();
		MythrilBlockID = config.getBlock("MythrilBlock", 2308).getInt();
		AugiteBlockID = config.getBlock("AugiteBlock", 2309).getInt();
		
		DraviteLeavesID = config.getBlock("DraviteLeaves", 2310).getInt();
		AzuriteLeavesID = config.getBlock("AzuriteLeaves", 2311).getInt();
		UviteLeavesID = config.getBlock("UviteLeaves", 2312).getInt();
		MythrilLeavesID = config.getBlock("MythrilLeaves", 2313).getInt();
		AugiteLeavesID = config.getBlock("AugiteLeaves", 2314).getInt();

		DraviteLogID = config.getBlock("DraviteLog", 2315).getInt();
		AzuriteLogID = config.getBlock("AzuriteLog", 2316).getInt();
		UviteLogID = config.getBlock("UviteLog", 2317).getInt();
		MythrilLogID = config.getBlock("MythrilLog", 2318).getInt();
		AugiteLogID = config.getBlock("AugiteLog", 2319).getInt();
		
		DraviteOreID = config.getBlock("DraviteOre", 2320).getInt();
		AzuriteOreID = config.getBlock("AzuriteOre", 2321).getInt();
		UviteOreID = config.getBlock("UviteOre", 2322).getInt();
		MythrilOreID = config.getBlock("MythrilOre", 2323).getInt();
		AugiteOreID = config.getBlock("AugiteOre", 2324).getInt();
		
		AzuriteVineID = config.getBlock("AzuriteVine", 2325).getInt();
		
		ArcanaPortalID = config.getBlock("ArcanaPortal", 2399).getInt();
		ArcanaPortalFrameID = config.getBlock("ArcanaPortalFrame", 2400).getInt();
		MoltenFurnaceID = config.getBlock("MoltenFurnace", 2401).getInt();
		MoltenFurnaceOnID = config.getBlock("MoltenFurnaceOn", 2402).getInt();
		MoonlightFurnaceID = config.getBlock("MoonlightFurnace", 2403).getInt();
		MoonlightFurnaceOnID = config.getBlock("MoonlightFurnaceOn", 2404).getInt();
		OceanFireFurnaceID = config.getBlock("OceanFireFurnace", 2405).getInt();
		OceanFireFurnaceOnID = config.getBlock("OceanFireFurnaceOn", 2406).getInt();
		WhiteFireFurnaceID = config.getBlock("WhiteFireFurnace", 2407).getInt();
		WhiteFireFurnaceOnID = config.getBlock("WhiteFireFurnaceOn", 2408).getInt();
		GreenLightFurnaceID = config.getBlock("GreenLightFurnace", 2409).getInt();
		GreenLightFurnaceOnID = config.getBlock("GreenLightFurnaceOn", 2410).getInt();
		DemonFurnaceID = config.getBlock("DemonFurnace", 2411).getInt();
		DemonFurnaceOnID = config.getBlock("DemonFurnaceOn", 2412).getInt();
		ArcaniumOreID = config.getBlock("ArcaniumOre", 2413).getInt();
		StarBridgeID = config.getBlock("StarBridge", 2414).getInt();
		StarBridgeOnID = config.getBlock("StarBridgeOn", 2415).getInt();
		ExtractorID = config.getBlock("Extractor", 2416).getInt();
		HeatTrapID = config.getBlock("HeatTramp", 2417).getInt();
		HeatTrapOnID = config.getBlock("HeatTrapOn", 2418).getInt();
		AncientBricksID = config.getBlock("AncientBrick", 2419).getInt();
		DegradedBricksID = config.getBlock("DegradedBrick", 2420).getInt();
		ArcaniumMetalID = config.getBlock("ArcaniumMetal", 2421).getInt();
		ArcaniumPowerID = config.getBlock("ArcaniumPower", 2422).getInt();
		AncientStoneID = config.getBlock("AncientStone", 2423).getInt();
		SoulStoneID = config.getBlock("SoulStone", 2424).getInt();
		DungeonLampID = config.getBlock("DungeonLamp", 2425).getInt();
		AncientTileID = config.getBlock("AncientTile", 2426).getInt();
		SoulSludgeID = config.getBlock("SoulSludge", 2427).getInt();
		ParasectaAltarID = config.getBlock("ParasectaAltar", 2428).getInt();
		DramixAltarID = config.getBlock("DramixAltar", 2429).getInt();
		RoamerSpawnerID = config.getBlock("RoamerSpawner", 2430).getInt();
		DeathcryxSpawnerID = config.getBlock("DeathcryxSpawner", 2431).getInt();
		DeathHoundSpawnerID = config.getBlock("DeathHoundSpawner", 2432).getInt();
		RazorbackSpawnerID = config.getBlock("RazorbackSpawner", 2433).getInt();
		LivingStatueSpawnerID = config.getBlock("LivingStatueSpawner", 2434).getInt();
		DungeonPrisonerSpawnerID = config.getBlock("DungeonPrisonerSpawner", 2435).getInt();
		ArcaniteTubesID = config.getBlock("ArcaniteTubes", 2436).getInt();
		ArcaniteRailsID = config.getBlock("ArcaniteRails", 2437).getInt();
		OreDoor1BlockID = config.getBlock("OreDoor1", 2438).getInt();
		OreDoor2BlockID = config.getBlock("OreDoor2", 2439).getInt();
		OreDoor3BlockID = config.getBlock("OreDoor3", 2440).getInt();
		OreDoor4BlockID = config.getBlock("OreDoor4", 2441).getInt();
		
		dreamstoneID = config.getBlock("DreamStone", 2500).getInt();
    	vetheaPortalID = config.getBlock("vetheaPortal", 2502).getInt();
        dreamwoodID = config.getBlock("dreamwood", 2503).getInt();
        dreamwoodLeavesID = config.getBlock("dreamwoodLeaves", 2504).getInt();
        dreambricksID = config.getBlock("dreambricks", 2505).getInt();
        lunastoneID = config.getBlock("lunastone", 2506).getInt();
        lunabricksID = config.getBlock("lunabricks", 2507).getInt();
        metalCagingID = config.getBlock("metalCaging", 2508).getInt();
        dreamlampID = config.getBlock("dreamlamp", 2509).getInt();
        dreamlampOnID = config.getBlock("dreamlampOn", 2510).getInt();
        weedwoodVineID = config.getBlock("weedwoodVine", 2511).getInt();
        blossomingWeedwoodVineID = config.getBlock("blossomingWeedwoodVine", 2512).getInt();
        cryptWallID = config.getBlock("cryptWall", 2513).getInt();
        smoothGlassID = config.getBlock("smoothGlass", 2514).getInt();
        villageLampID = config.getBlock("villageLamp", 2515).getInt();
        infusionTableID = config.getBlock("infusionTable", 2516).getInt();
        cellLampID = config.getBlock("cellLamp", 2517).getInt();
        barredDoorID = config.getBlock("barredDoor", 2518).getInt();
        firecrystalID = config.getBlock("firecrystal", 2519).getInt();
        firelightID = config.getBlock("firelight", 2520).getInt();
        hyrewoodID = config.getBlock("hyrewood", 2521).getInt();
        mintwoodLeavesID = config.getBlock("mintwoodLeaves", 2523).getInt();
        firewallID = config.getBlock("firewall", 2524).getInt();
        karosHeatTileRedID = config.getBlock("karosHeatTileRed", 2525).getInt();
        karosHeatTileGreenID = config.getBlock("karosHeatTileGreen", 2526).getInt();
        karosCannonID = config.getBlock("karosCannon", 2527).getInt();
        helioticBeamID = config.getBlock("helioticBeam", 2528).getInt();
        cryptFloorID = config.getBlock("cryptFloor", 2529).getInt();
        firewoodID = config.getBlock("firewood", 2530).getInt();
        chamberWallID = config.getBlock("chamberWall", 2531).getInt();
        chamberWall1ID = config.getBlock("chamberWall1", 2532).getInt();
        chamberWall2ID = config.getBlock("chamberWall2", 2533).getInt();
        bacterialAcidID = config.getBlock("bacterialAcid", 2534).getInt();
        gemtopPurpleID = config.getBlock("gemtops", 2535).getInt();
        yellowDulahID = config.getBlock("yellowDulah", 2536).getInt();
        blockAcidID = config.getBlock("acidBlock", 2537).getInt();
        hallWallID = config.getBlock("hallWall", 2538).getInt();
        wreckAltarID = config.getBlock("wreckAltar", 2539).getInt();
        raglokAltarID = config.getBlock("raglokAltar", 2540).getInt();
        karosAltarID = config.getBlock("karosAltar", 2541).getInt();
        lunicAltarID = config.getBlock("lunicAltar", 2542).getInt();
        hiveWallID = config.getBlock("hiveWall", 2543).getInt();
        quadroticAltarID = config.getBlock("quadroticAltar", 2544).getInt();
        everstoneID = config.getBlock("everstone", 2545).getInt();
        lunicAcidID = config.getBlock("lunicAcid", 2546).getInt();
        firewoodLeavesID = config.getBlock("firewoodLeaves", 2547).getInt();
        hyrewoodLeavesID = config.getBlock("hyrewoodLeaves", 2548).getInt();
        gemtopGreenID = config.getBlock("gemtopsGreen", 2549).getInt();
        greenDulahID = config.getBlock("greenDulah", 2550).getInt();
        mintwoodID = config.getBlock("mintwood", 2551).getInt();
        lightFirewoodLeavesID = config.getBlock("lightFirerwoodLeaves", 2552).getInt();
        cracklespikeID = config.getBlock("cracklespike", 2553).getInt();
        ferniteID = config.getBlock("fernite", 2554).getInt();
        bulatobeID = config.getBlock("bulatobe", 2555).getInt();
        shineGrassID = config.getBlock("shineGrass", 2556).getInt();
        shimmerID = config.getBlock("shimmer", 2557).getInt();
        dreamglowID = config.getBlock("dreamglow", 2558).getInt();
        hyrewoodVineID = config.getBlock("hyrewoodVine", 2559).getInt();
        dreambricks2ID = config.getBlock("dreambricks2", 2560).getInt();
        whiteEverstoneID = config.getBlock("whiteEverstone", 2561).getInt();
        darkEverstoneID = config.getBlock("darkEverstone", 2562).getInt();
        karosBricksID = config.getBlock("karosBricks", 2563).getInt();
        karosBricks2ID = config.getBlock("karosBricks2", 2564).getInt();

        biphronSpawnerID = config.getBlock("briphronSpawner", 2565).getInt();
        gorgosionSpawnerID = config.getBlock("gorgosionSpawner", 2566).getInt();
        twinsSpawnerID = config.getBlock("twinsSpawner", 2567).getInt();
        duoSpawnerID = config.getBlock("duoSpawner", 2568).getInt();
        vermenousSpawnerID = config.getBlock("vermenousSpawner", 2569).getInt();
        dreamwreckerSpawnerID = config.getBlock("dreamwreckerSpawner", 2570).getInt();
        lorgaSpawnerID = config.getBlock("lorgaSpawner", 2571).getInt();
        hungerstone1ID = config.getBlock("hungerstone1", 2572).getInt();
        hungerstone2ID = config.getBlock("hungerstone2", 2573).getInt();
        purpleFireID = config.getBlock("PurpleFire", 2574).getInt();
        		
		config.save();
    }
}