package net.divinerpg.helper.config;

import java.io.File;

import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

public class ItemConfigHelper {

	public static int SnowflakeShurikenID;
	public static int FrossivenceID;
	public static int SerenadeOfIceID;
	public static int GlacierSwordID;
	public static int IcicleBowID;
	public static int IcicleBaneID;
	public static int FrostclawCannonID;
	public static int FractiteCannonID;
	public static int FrostkingSwordID;
	public static int SoundOfCarolsID;
	public static int EndericeID;
	public static int SnowstormBowID;
	public static int IcineSwordID;
	public static int FrozenMaulID;
	public static int SnowslashID;
	public static int PeppermintsID;
	public static int EggNogID;
	public static int ChocolateLogID;
	public static int SnowconesID;
	public static int FruitCakeID;
	public static int SnowflakeID;
	public static int SantaHeadID;
	public static int SantaBodyID;
	public static int SantaLegsID;
	public static int SantaBootsID;

	public static int BlueFireBowID;
	public static int fractiteCannonID;
	
	public static int bedrockMaulID;
	public static int soundOfMusicID;
	public static int greenShardID;
	public static int shurikenID;
	public static int namkormiraID;
	public static int slimeSwordID;
	public static int shadowBowID;
	public static int crabClawCannonID;
	public static int frostCannonID;
	public static int frostSwordID;
	public static int divineswordID;
	public static int sandSlashID;
	public static int blueShardID;
	public static int iceShardID;
	public static int yellowShardID;

	public static int serenadeStrikerID;
	public static int serenadeOfLifeID;
	public static int serenadeOfDeathID;

	public static int divineHelmID;
	public static int divineBodyID;
	public static int divineLegsID;
	public static int divineBootsID;

	public static int enderSwordID;
	public static int enderSwordYellowID;
	public static int enderSwordGreenID;
	public static int enderSwordRedID;
	public static int enderSwordBlueID;
	public static int enderSwordBlackID;

	public static int bluefirebowID;
	public static int rupeeID;
	public static int tomatoID;
	public static int tomatoSeedsID;
	public static int purpleFireID;
	public static int jackOManBootsID;
	public static int jackOManLegsID;
	public static int jackOManBodyID;
	public static int jackOManHeadID;
	public static int scytheID;
	public static int sharkAnchorID;
	public static int healingStoneID;

	public static int grimReaperHeadID;
	public static int grimReaperBodyID;
	public static int grimReaperLegsID;
	public static int grimReaperBootsID;
	public static int jungleStoneID;
	public static int divineStoneID;
	public static int iceStoneID;
	public static int enderStoneID;
	public static int moltenStoneID;
	public static int corruptedStoneID;
	public static int blueFireStoneID;

	public static int palavenceID;
	public static int arlemiteStabberID;
	public static int rupeeRapierID;
	public static int realmiteSwordID;
	public static int poisonSaberID;
	public static int infernoSwordID;
	public static int bedrockSwordID;
	public static int aquaticDaggerID;
	public static int aquaticTridentID;
	public static int oceanKnifeID;
	public static int aquatonID;
	public static int sharkSwordID;
	public static int crabclawMaulID;
	public static int deathBringerID;
	public static int corruptedMaulID;
	public static int scorchingSwordID;
	public static int bluefireSwordID;
	public static int divineSwordID;
	public static int bloodgemSwordID;
	public static int moltenSwordID;
	public static int vileStormID;
	public static int bowHeadAnchor;
	public static int crabAnchorID;
	public static int bowheadCannonID;
	public static int maelstromID;
	public static int ghastCannonID;
	public static int corruptCannonID;

	public static int massivenceID;
    public static int seranadeDeathID;
    public static int serenadeHealthID;
    public static int growthSerenadeID;
    public static int mailStromID;
    public static int clawAnchorID;
    public static int bowheadAnchorID;
    public static int vialStormID;
    public static int infernobowID;
    public static int crabClawMaulID;
    public static int rupeeSwordID;
    public static int passivenceID;
    public static int angelicBodyID;
    public static int angelicHeadID;
    public static int angelicLegsID;
    public static int angelicBootsID;
    public static int divineHeadID;
    public static int purpleShardID;
    public static int redShardID;
    public static int corruptedShardsID;
    
	public static int twilightClockID;
	
	public static int DraviteGemID;
	public static int DraviteChunkID;
	public static int DraviteFragmentsID;
	public static int DraviteDustID;
	public static int DraviteBladeID;
	public static int DravitePhaserID;
	public static int DraviteBlitzID;
	public static int DraviteBowID;
	public static int DraviteHelmetID;
	public static int DraviteBootsID;
	public static int DravitelegsID;
	public static int DraviteChestID;
	public static int DraviteSlicerID;
	public static int DraviteSoulID;
	public static int draviteSparklesID;
	public static int DraviteShardsID;

	public static int UviteGemID;
	public static int UviteChunkID;
	public static int UviteFragmentsID;
	public static int UviteDustID;
	public static int UviteBladeID;
	public static int UvitePhaserID;
	public static int UviteBlitzID;
	public static int UviteBowID;
	public static int UviteHelmetID;
	public static int UviteBootsID;
	public static int UvitelegsID;
	public static int UviteChestID;
	public static int UviteSlicerID;
	public static int UviteSoulID;

	public static int AzuriteGemID;
	public static int AzuriteChunkID;
	public static int AzuriteFragmentsID;
	public static int AzuriteDustID;
	public static int AzuriteBladeID;
	public static int AzuritePhaserID;
	public static int AzuriteBlitzID;
	public static int AzuriteBowID;
	public static int AzuriteHelmetID;
	public static int AzuriteBootsID;
	public static int AzuritelegsID;
	public static int AzuriteChestID;
	public static int AzuriteSlicerID;
	public static int AzuriteSoulID;
	public static int AzuriteArrowID;

	public static int MythrilGemID;
	public static int MythrilChunkID;
	public static int MythrilFragmentsID;
	public static int MythrilDustID;
	public static int MythrilBladeID;
	public static int MythrilPhaserID;
	public static int MythrilBlitzID;
	public static int MythrilBowID;
	public static int MythrilHelmetID;
	public static int MythrilBootsID;
	public static int MythrillegsID;
	public static int MythrilChestID;
	public static int MythrilSlicerID;
	public static int MythrilSoulID;

	public static int AugiteGemID;
	public static int AugiteChunkID;
	public static int AugiteFragmentsID;
	public static int AugiteDustID;
	public static int AugiteBladeID;
	public static int AugitePhaserID;
	public static int AugiteBlitzID;
	public static int AugiteBowID;
	public static int AugiteHelmetID;
	public static int AugiteBootsID;
	public static int AugitelegsID;
	public static int AugiteChestID;
	public static int AugiteSlicerID;
	public static int AugiteSoulID;

	public static int HaliteBladeID;
	public static int HalitePhaserID;
	public static int HaliteBlitzID;
	public static int HaliteBowID;
	public static int HaliteHelmetID;
	public static int HaliteBootsID;
	public static int HalitelegsID;
	public static int HaliteChestID;
	public static int HaliteSlicerID;

	public static int FuryArrowID;
	public static int TwilightClockID;
	public static int TwilightBowID;
	public static int blueSeedsID;
	public static int magicMeatID;
	public static int empoweredMeatID;
	public static int enrichedMagicMeatID;
	public static int cookedEmpoweredMeatID;
	public static int purpleSeedsID;
	public static int pinkSeedsID;		
	public static int fireThrowerID;


    
    public static int oreDoorItem1ID;
    public static int oreDoor2ItemID;
    public static int oreDoor3ItemID;
    public static int oreDoor4ItemID;
    public static int key1ID;
    public static int key2ID;
    public static int key3ID;
    public static int key4ID;
    public static int fireStockintID;
    public static int pinFlyintID;
    public static int hitchakintID;
    public static int veilointID;
    public static int lamonaintID;
    public static int aquamarineintID;
    public static int marsineintID;
    public static int hitchakSeedsID;
    public static int eucalyptusRootSeedsID;
    public static int veiloSeedsID;
    public static int lamonaSeedsID;
    public static int aquamarineSeedsID;
    public static int marsineSeedsID;
    public static int pinFlySeedsID;
    public static int fireStockSeedsID;
    public static int arcaniumID;
    public static int collectorID;
    public static int fyracryxSpawnerID;
    public static int fireflyID;
    public static int starfallID;
    public static int reflectorID;
    public static int stormSwordID;
    public static int staffOfStarlightID;
    public static int wraithbaneID;
    public static int captiansSparklerID;
    public static int shadowSwordID;
    public static int enderScepterID;
    public static int grenadeLauncherID;
    public static int grenadeID;
    public static int meriksMissileID;
    public static int arcaniumSaberID;
    public static int liviciaSwordID;
    public static int paratikuSpawnerID;
    public static int seimerSpawnerID;
    public static int golemOfRejuvSpawnerID;
    public static int dungeonTokenID;
    public static int weakArcanaPotionID;
    public static int strongArcanaPotionID;
    public static int arcanaMusicBoxID;
    public static int orbOfLightID;
    public static int tarBucketID;
    public static int santaHeadID;
    public static int santaBodyID;
    public static int santaLegsID;
    public static int santaBootsID;
    public static int collectorFragmentsID;
    public static int arcaniumBucketID;
    public static int staffOfEnrichmentID;
    public static int kormaHeadID;
    public static int kormaBodyID;
    public static int kormaLegsID;
    public static int kormaBootsID;
    public static int vemosHeadID;
    public static int vemosBodyID;
    public static int vemosLegsID;
    public static int vemosBootsID;
    public static int wizardBookID;
    public static int fireStockItemID;
    public static int pinFlyItemID;
    public static int hitchakItemID;
    public static int veiloItemID;
    public static int lamonaItemID;
    public static int aquamarineItemID;
    public static int marsineItemID;
    
    public static int bloodGemID, arlemiteID, realmiteID, netheriteID, rupeeShovelID, rupeeAxeID, rupeeHoeID, rupeePickaxeID;
    public static int arlemiteShovelID, arlemiteAxeID, arlemiteHoeID, arlemitePickaxeID;
    public static int realmiteShovelID, realmiteAxeID, realmiteHoeID, realmitePickaxeID;
    public static int rupeeShickaxeID, arlemiteShickaxeID, TwilightAppleID;
    public static int hellStoneIngotID, purpleBlazeID, shadowBarID, netheriteChunkID, legendaryEnderEyeID;
    
    public static int realmiteHelmetID, realmiteBodyID, realmiteLegsID, realmiteBootsID;
    public static int arlemiteHelmetID, arlemiteBodyID, arlemiteLegsID, arlemiteBootsID;
    public static int rupeeHelmetID, rupeeBodyID, rupeeLegsID, rupeeBootsID;
    public static int infernalFlameID, baseSpawnCrystalID, SoulFiendSpawnCrystalID, VamacheronSpawnCrystalID, 
    TwilightDemonSpawnCrystalID, KarotSpawnCrystalID, DensosSpawnCrystalID;
    
    public static int hordeHornID, mysteriousClockID, watchingEyeID, callOfTheWatcherID, furyFireID;
    
    public static int shadowHelmetID, shadowBodyID, shadowLegsID, shadowBootsID;
    public static int aquaticHelmetID, aquaticBodyID, aquaticLegsID, aquaticBootsID;
    public static int krakenSkinID, krakenScaleID, shadowStoneID, homeTeleporterID; 
    
    public static int whaleFinID, purpleGlowTreeID, pinkGlowTreeID;
    public static int eliteRealHelmID, eliteRealBodyID, eliteRealLegsID, eliteRealBootsID;
    public static int krakenHelmID, krakenBodyID, krakenLegsID, krakenBootsID;
    public static int divineStickID, divineWoodAxeID, divineWoodPickID, divineWoodHoeID, divineWoodShovelID, divineWoodSwordID;
    public static int cyclopseEyeID, cyclopseBowID, cyclopseStaffID, cyclopseSwordID;
		
	public static void initConfig(FMLPreInitializationEvent event) {
		File file = new File(event.getModConfigurationDirectory(), "DivineRPGItems.cfg");
		Configuration config = new Configuration(file);
		
		config.load();

		SnowflakeShurikenID = config.getItem("Snowflake Shuriken", 3000).getInt();
		FrossivenceID = config.getItem("Frossivence", 3001).getInt();
		SerenadeOfIceID = config.getItem("Serenade Of Ice", 3002).getInt();
		GlacierSwordID = config.getItem("Glacier Sword", 3003).getInt();
		IcicleBowID = config.getItem("Icicle Bow", 3004).getInt();
		IcicleBaneID = config.getItem("Icicle Bane", 3005).getInt();
		FrostclawCannonID = config.getItem("Frostclaw Cannon", 3006).getInt();
		FractiteCannonID = config.getItem("Fractite Cannon", 3007).getInt();
		FrostkingSwordID = config.getItem("Frostking Sword", 3008).getInt();
		SoundOfCarolsID = config.getItem("Sound of Carols", 3009).getInt();
		EndericeID = config.getItem("Enderice", 3010).getInt();
		SnowstormBowID = config.getItem("Snowstorm Bow", 3011).getInt();
		IcineSwordID = config.getItem("Icine Sword", 3012).getInt();
		FrozenMaulID = config.getItem("Frozen Maul", 3013).getInt();
		SnowslashID = config.getItem("Snowslash", 3014).getInt();
		PeppermintsID = config.getItem("Peppermints", 3016).getInt();
		EggNogID = config.getItem("Egg Nog", 3017).getInt();
		ChocolateLogID = config.getItem("Chocolate Log", 3018).getInt();
		SnowconesID = config.getItem("Snowcones", 3019).getInt();
		FruitCakeID = config.getItem("Fruit Cake", 3020).getInt();
		SnowflakeID = config.getItem("Snowflake", 3021).getInt();
		SantaHeadID = config.getItem("Santa Head", 3022).getInt();
		SantaBodyID = config.getItem("Santa Body", 3023).getInt();
		SantaLegsID = config.getItem("Santa Legs", 3024).getInt();
		SantaBootsID = config.getItem("Santa Boots", 3025).getInt();
		BlueFireBowID = config.getItem("BlueFire Bow", 3026).getInt();
		fractiteCannonID = config.getItem("Fractite Cannon", 3027).getInt();
		
		bedrockMaulID = config.getItem("bedrockMaul", 3028).getInt();
		soundOfMusicID = config.getItem("soundOfMusic", 3029).getInt();
		greenShardID = config.getItem("greenShard", 3030).getInt();
		shurikenID = config.getItem("shuriken", 3040).getInt();
		namkormiraID = config.getItem("namkormira", 3041).getInt();
		serenadeStrikerID = config.getItem("serenadeStriker", 3042).getInt();
		slimeSwordID = config.getItem("slimeSword", 3043).getInt();
		shadowBowID = config.getItem("shadowBow", 3044).getInt();
		crabClawCannonID = config.getItem("crabClawCannon", 3045).getInt();
		frostCannonID = config.getItem("frostCannon", 3046).getInt();
		frostSwordID = config.getItem("frostSword", 3047).getInt();
		divineswordID = config.getItem("divinesword", 3048).getInt();
		sandSlashID = config.getItem("sandSlash", 3049).getInt();
		blueShardID = config.getItem("blueShard", 3050).getInt();
		iceShardID = config.getItem("iceShard", 3051).getInt();
		yellowShardID = config.getItem("yellowShard", 3052).getInt();

		divineHelmID = config.getItem("divineHelm", 3053).getInt();
		divineBodyID = config.getItem("divineBody", 3054).getInt();
		divineLegsID = config.getItem("divineLegs", 3055).getInt();
		divineBootsID = config.getItem("divineBoots", 3056).getInt();
        divineHeadID = config.getItem("divineHeadID", 3057).getInt();

		enderSwordID = config.getItem("enderSword", 3058).getInt();
		enderSwordBlueID = config.getItem("enderSwordBlue", 3059).getInt();
		enderSwordBlackID = config.getItem("enderSwordDark", 3060).getInt();
		enderSwordGreenID = config.getItem("enderSwordGreen", 3061).getInt();
		enderSwordRedID = config.getItem("enderSwordRed", 3062).getInt();
		enderSwordYellowID = config.getItem("enderSwordYellow", 3063).getInt();


		bluefirebowID = config.getItem("bluefirebow", 3064).getInt();
		rupeeID = config.getItem("rupee", 3065).getInt();
		tomatoID = config.getItem("tomato", 3066).getInt();
		tomatoSeedsID = config.getItem("tomatoSeeds", 3067).getInt();
		purpleFireID = config.getItem("purpleFire", 3068).getInt();
		jackOManBootsID = config.getItem("jackOManBoots", 3069).getInt();
		jackOManLegsID = config.getItem("jackOManLegs", 3070).getInt();
		jackOManBodyID = config.getItem("jackOManBody", 3071).getInt();
		jackOManHeadID = config.getItem("jackOManHead", 3072).getInt();
		scytheID = config.getItem("scythe", 3073).getInt();
		sharkAnchorID = config.getItem("sharkAnchor", 3074).getInt();
		healingStoneID = config.getItem("healingStone", 3075).getInt();

		massivenceID = config.getItem("massivence", 3076).getInt();
		palavenceID = config.getItem("passivence", 3077).getInt();
		arlemiteStabberID = config.getItem("arlemiteStabber", 3078).getInt();
		rupeeRapierID = config.getItem("rupeeRapier", 3079).getInt();
		realmiteSwordID = config.getItem("realmiteSword", 3080).getInt();
		poisonSaberID = config.getItem("poisonSaber", 3081).getInt();
		twilightClockID = config.getItem("twilightClock", 3082).getInt();


		seranadeDeathID = config.getItem("seranadeDeathID", 3083).getInt();
		serenadeHealthID = config.getItem("serenadeHealthID", 3084).getInt();
		growthSerenadeID = config.getItem("growthSerenadeID", 3085).getInt();
		mailStromID = config.getItem("mailStromID", 3086).getInt();
        clawAnchorID = config.getItem("clawAnchorID", 3087).getInt();
        bowheadAnchorID = config.getItem("bowheadAnchorID", 3088).getInt();
        bowheadAnchorID = config.getItem("bowheadAnchorID", 3089).getInt();
        crabClawMaulID = config.getItem("crabClawMaulID", 3090).getInt();
        rupeeSwordID = config.getItem("clawAnchorID", 3091).getInt();
        passivenceID = config.getItem("passivenceID", 3092).getInt();

        angelicBodyID = config.getItem("angelicBodyID", 3093).getInt();
        angelicHeadID = config.getItem("angelicHeadID", 3094).getInt();
        angelicLegsID = config.getItem("angelicLegsID", 3095).getInt();
        angelicBootsID = config.getItem("angelicBootsID", 3096).getInt();
        purpleShardID = config.getItem("purpleShardID", 3097).getInt();
        redShardID = config.getItem("redShardID", 3098).getInt();
        corruptedShardsID = config.getItem("corruptedShardsID", 3099).getInt();
        
        moltenSwordID = config.getItem("MoltenSword", 3100).getInt();
        
        DraviteGemID = config.getItem("Dravite Gem", 3101).getInt();
		DraviteChunkID = config.getItem("Dravite Chunk", 3102).getInt();
		DraviteFragmentsID = config.getItem("Dravite Fragments", 3103).getInt();
		DraviteDustID = config.getItem("Dravite Dust", 3104).getInt();
		DraviteBladeID = config.getItem("Dravite Blade", 3105).getInt();
		DravitePhaserID = config.getItem("Dravite Phaser", 3106).getInt();
		DraviteBlitzID = config.getItem("Dravite Blitz", 3107).getInt();
		DraviteBowID = config.getItem("Dravite Bow", 3108).getInt();
		DraviteHelmetID = config.getItem("Dravite Helmet", 3109).getInt();
		DraviteBootsID = config.getItem("Dravite Boots", 3110).getInt();
		DravitelegsID = config.getItem("Dravite Legs", 3111).getInt();
		DraviteChestID = config.getItem("Dravite Chest", 3112).getInt();
		DraviteSlicerID = config.getItem("Dravite Slicer", 3113).getInt();
		DraviteSoulID = config.getItem("Dravite Soul", 3114).getInt();
		draviteSparklesID = config.getItem("Dravite Soul", 3115).getInt();
		DraviteShardsID = config.getItem("Dravite Soul", 3116).getInt();

		AzuriteGemID = config.getItem("Azurite Gem", 3117).getInt();
		AzuriteChunkID = config.getItem("Azurite Chunk", 3118).getInt();
		AzuriteFragmentsID = config.getItem("Azurite Fragments", 3119).getInt();
		AzuriteDustID = config.getItem("Azurite Dust", 3120).getInt();
		AzuriteBladeID = config.getItem("Azurite Blade", 3121).getInt();
		AzuritePhaserID = config.getItem("Azurite Phaser", 3122).getInt();
		AzuriteBlitzID = config.getItem("Azurite Blitz", 3123).getInt();
		AzuriteBowID = config.getItem("Azurite Bow", 3124).getInt();
		AzuriteHelmetID = config.getItem("Azurite Helmet", 3125).getInt();
		AzuriteBootsID = config.getItem("Azurite Boots", 3126).getInt();
		AzuritelegsID = config.getItem("Azurite Legs", 3127).getInt();
		AzuriteChestID = config.getItem("Azurite Chest", 3128).getInt();
		AzuriteSlicerID = config.getItem("Azurite Slicer", 3129).getInt();
		AzuriteSoulID = config.getItem("Azurite Soul", 3130).getInt();
		AzuriteArrowID = config.getItem("Dravite Soul", 3131).getInt();

		UviteGemID = config.getItem("Uvite Gem", 3132).getInt();
		UviteChunkID = config.getItem("Uvite Chunk", 3133).getInt();
		UviteFragmentsID = config.getItem("Uvite Fragments", 3134).getInt();
		UviteDustID = config.getItem("Uvite Dust", 3135).getInt();
		UviteBladeID = config.getItem("Uvite Blade", 3136).getInt();
		UvitePhaserID = config.getItem("Uvite Phaser", 3137).getInt();
		UviteBlitzID = config.getItem("Uvite Blitz", 3138).getInt();
		UviteBowID = config.getItem("Uvite Bow", 3139).getInt();
		UviteHelmetID = config.getItem("Uvite Helmet", 3140).getInt();
		UviteBootsID = config.getItem("Uvite Boots", 3141).getInt();
		UvitelegsID = config.getItem("Uvite Legs", 3142).getInt();
		UviteChestID = config.getItem("Uvite Chest", 3143).getInt();
		UviteSlicerID = config.getItem("Uvite Slicer", 3144).getInt();
		UviteSoulID = config.getItem("Uvite Soul", 3145).getInt();

		MythrilGemID = config.getItem("Mythril Gem", 3146).getInt();
		MythrilChunkID = config.getItem("Mythril Chunk", 3147).getInt();
		MythrilFragmentsID = config.getItem("Mythril Fragments", 3148).getInt();
		MythrilDustID = config.getItem("Mythril Dust", 3149).getInt();
		MythrilBladeID = config.getItem("Mythril Blade", 3150).getInt();
		MythrilPhaserID = config.getItem("Mythril Phaser", 3151).getInt();
		MythrilBlitzID = config.getItem("Mythril Blitz", 3152).getInt();
		MythrilBowID = config.getItem("Mythril Bow", 3153).getInt();
		MythrilHelmetID = config.getItem("Mythril Helmet", 3154).getInt();
		MythrilBootsID = config.getItem("Mythril Boots", 3155).getInt();
		MythrillegsID = config.getItem("Mythril Legs", 3156).getInt();
		MythrilChestID = config.getItem("Mythril Chest", 3157).getInt();
		MythrilSlicerID = config.getItem("Mythril Slicer", 3158).getInt();
		MythrilSoulID = config.getItem("Mythril Soul", 3159).getInt();

		AugiteGemID = config.getItem("Augite Gem", 3160).getInt();
		AugiteChunkID = config.getItem("Augite Chunk", 3161).getInt();
		AugiteFragmentsID = config.getItem("Augite Fragments", 3162).getInt();
		AugiteDustID = config.getItem("Augite Dust", 3163).getInt();
		AugiteBladeID = config.getItem("Augite Blade", 3164).getInt();
		AugitePhaserID = config.getItem("Augite Phaser", 3165).getInt();
		AugiteBlitzID = config.getItem("Augite Blitz", 3166).getInt();
		AugiteBowID = config.getItem("Augite Bow", 3167).getInt();
		AugiteHelmetID = config.getItem("Augite Helmet", 3168).getInt();
		AugiteBootsID = config.getItem("Augite Boots", 3169).getInt();
		AugitelegsID = config.getItem("Augite Legs", 3170).getInt();
		AugiteChestID = config.getItem("Augite Chest", 3171).getInt();
		AugiteSlicerID = config.getItem("Augite Slicer", 3172).getInt();
		AugiteSoulID = config.getItem("Augite Soul", 3173).getInt();

		HaliteBladeID = config.getItem("Halite Blade", 3174).getInt();
		HalitePhaserID = config.getItem("Halite Phaser", 3175).getInt();
		HaliteBlitzID = config.getItem("Halite Blitz", 3176).getInt();
		HaliteBowID = config.getItem("Halite Bow", 3177).getInt();
		HaliteHelmetID = config.getItem("Halite Helmet", 3178).getInt();
		HaliteBootsID = config.getItem("Halite Boots", 3179).getInt();
		HalitelegsID = config.getItem("Halite Legs", 3180).getInt();
		HaliteChestID = config.getItem("Halite Chest", 3181).getInt();
		HaliteSlicerID = config.getItem("Halite Slicer", 3182).getInt();

		FuryArrowID = config.getItem("FuryArrow", 3183).getInt();
		TwilightClockID = config.getItem("TwilightClock", 3184).getInt();
		TwilightBowID = config.getItem("TwilightBow", 3185).getInt();
		blueSeedsID = config.getItem("blueSeeds", 3186).getInt();
		magicMeatID = config.getItem("magicMeat", 3187).getInt();
		empoweredMeatID = config.getItem("empoweredMeat", 3188).getInt();
		enrichedMagicMeatID = config.getItem("enrichedMagicMeat", 3189).getInt();
		cookedEmpoweredMeatID = config.getItem("cookedEmpoweredMeat", 3190).getInt();
		purpleSeedsID = config.getItem("purpleSeeds", 3191).getInt();
		pinkSeedsID = config.getItem("pinkSeeds", 3192).getInt();		
		fireThrowerID = config.getItem("fireThrower", 3193).getInt();
		
	
        key1ID = config.getItem("key1", 3345).getInt();
        key2ID = config.getItem("key2", 3346).getInt();
        key3ID = config.getItem("key3", 3347).getInt();
        key4ID = config.getItem("key4", 3348).getInt();
        oreDoorItem1ID = config.getItem("oredooritem", 3349).getInt();
        oreDoor2ItemID = config.getItem("oredooritem2", 3350).getInt();
        oreDoor3ItemID = config.getItem("oredooritem3", 3351).getInt();
        oreDoor4ItemID = config.getItem("oredooritem4", 3352).getInt();
        tarBucketID = config.getItem("tarbucket", 3353).getInt();
        hitchakItemID = config.getItem("hitchakItem", 3354).getInt();
        fireStockItemID = config.getItem("firestockitem", 3355).getInt();
        pinFlyItemID = config.getItem("pinflyItem", 3356).getInt();
        veiloItemID = config.getItem("veiloItem", 3357).getInt();
        lamonaItemID = config.getItem("lamonaItemID", 3358).getInt();
        aquamarineItemID = config.getItem("aquamarineItem", 3359).getInt();
        marsineItemID = config.getItem("marsineItem", 3360).getInt();
        hitchakSeedsID = config.getItem("hitchakSeeds", 3361).getInt();
        eucalyptusRootSeedsID = config.getItem("eucalyptusRootSeeds", 3362).getInt();
        veiloSeedsID = config.getItem("veiloSeeds", 3363).getInt();
        lamonaSeedsID = config.getItem("lamonaSeeds", 3364).getInt();
        aquamarineSeedsID = config.getItem("aquamarineSeeds", 3365).getInt();
        marsineSeedsID = config.getItem("marsineSeeds", 3366).getInt();
        pinFlySeedsID = config.getItem("pinflyseeds", 3367).getInt();
        fireStockSeedsID = config.getItem("firestockseeds", 3368).getInt();
        arcaniumID = config.getItem("arcanium", 3369).getInt();
        fyracryxSpawnerID = config.getItem("fyracryxSpawner", 3370).getInt();
        fireflyID = config.getItem("firefly", 3371).getInt();
        starfallID = config.getItem("starfall", 3372).getInt();
        reflectorID = config.getItem("reflector", 3373).getInt();
        stormSwordID = config.getItem("stormSword", 3374).getInt();
        staffOfStarlightID = config.getItem("staffOfStarlight", 3375).getInt();
        wraithbaneID = config.getItem("wraithbane", 3376).getInt();
        captiansSparklerID = config.getItem("captiansSparkler", 3377).getInt();
        shadowSwordID = config.getItem("shadowSword", 3376).getInt();
        enderScepterID = config.getItem("enderScepter", 3377).getInt();
        grenadeLauncherID = config.getItem("grenadeLauncher", 3378).getInt();
        grenadeID = config.getItem("grenade", 3379).getInt();
        meriksMissileID = config.getItem("meriksMissile", 3380).getInt();
        arcaniumSaberID = config.getItem("arcaniumSaber", 3381).getInt();
        paratikuSpawnerID = config.getItem("paratikuSpawner", 3382).getInt();
        seimerSpawnerID = config.getItem("seimerSpawner", 3383).getInt();
        golemOfRejuvSpawnerID = config.getItem("golemOfRejuvSpawner", 3384).getInt();
        dungeonTokenID = config.getItem("dungeonToken", 3385).getInt();
        liviciaSwordID = config.getItem("liviciaSword", 3386).getInt();
        vemosHeadID = config.getItem("vemoshead", 3387).getInt();
        vemosBodyID = config.getItem("vemosbody", 3388).getInt();
        vemosLegsID = config.getItem("vemoslegs", 3389).getInt();
        vemosBootsID = config.getItem("vemosboots", 3390).getInt();
        kormaHeadID = config.getItem("kormashead", 3391).getInt();
        kormaBodyID = config.getItem("kormabody", 3392).getInt();
        kormaLegsID = config.getItem("kormalegs", 3393).getInt();
        kormaBootsID = config.getItem("kormaboots", 3394).getInt();
        wizardBookID = config.getItem("wizardbook", 3395).getInt();
        arcaniumBucketID = config.getItem("arcaniumbucket", 3396).getInt();
        collectorID = config.getItem("collector", 3397).getInt();
        collectorFragmentsID = config.getItem("collectorfragments", 3398).getInt();
        orbOfLightID = config.getItem("orboflight", 3399).getInt();
        weakArcanaPotionID = config.getItem("weakarcanapotion", 3400).getInt();
        strongArcanaPotionID = config.getItem("strongarcanapotion", 3401).getInt();
        staffOfEnrichmentID = config.getItem("staffofenrichment", 3402).getInt();
        
        bloodGemID = config.getItem("BloodGem", 3403).getInt();
		arlemiteID = config.getItem("Arlemite", 3404).getInt();
		realmiteID = config.getItem("Realmite", 3405).getInt();
		netheriteID = config.getItem("Netherite", 3406).getInt();
		rupeeShovelID = config.getItem("RupeeShovel", 3407).getInt();
		rupeeAxeID = config.getItem("RupeeAxe", 3408).getInt();
		rupeeHoeID = config.getItem("RupeeHoe", 3409).getInt();
		rupeePickaxeID = config.getItem("RupeePickaxe", 3410).getInt();
		arlemiteShovelID = config.getItem("ArlemiteShovel", 3411).getInt();
		arlemiteAxeID = config.getItem("ArlemiteAxe", 3412).getInt();
		arlemiteHoeID = config.getItem("ArlemiteHoe", 3413).getInt();
		arlemitePickaxeID = config.getItem("ArlemitePickaxe", 3414).getInt();
		realmiteShovelID = config.getItem("RealmiteShovel", 3415).getInt();
		realmiteAxeID = config.getItem("RealmiteAxe", 3416).getInt();
		realmiteHoeID = config.getItem("RealmiteHoe", 3417).getInt();
		realmitePickaxeID = config.getItem("RealmitePickaxe", 3418).getInt();
		rupeeShickaxeID = config.getItem("RupeeShickaxe", 3419).getInt();
		arlemiteShickaxeID = config.getItem("ArlemiteShickaxe", 3420).getInt();
		hellStoneIngotID = config.getItem("HellstoneIngot", 3421).getInt();
		purpleBlazeID = config.getItem("PurpleBlaze", 3422).getInt();
		shadowBarID = config.getItem("ShadowBar", 3423).getInt();
		netheriteChunkID = config.getItem("NetheriteChunk", 3424).getInt();
		legendaryEnderEyeID = config.getItem("LegendaryEnderEye", 3425).getInt();
		
		realmiteHelmetID = config.getItem("RealmiteHelmet", 3426).getInt();
		realmiteBodyID = config.getItem("RealmiteBody", 3427).getInt();
		realmiteLegsID = config.getItem("RealmiteLegs", 3428).getInt();
		realmiteBootsID = config.getItem("RealmiteBoots", 3429).getInt();
		arlemiteHelmetID = config.getItem("ArlemiteHelmet", 3430).getInt();
		arlemiteBodyID = config.getItem("ArlemiteBody", 3431).getInt();
		arlemiteLegsID = config.getItem("ArlemiteLegs", 3432).getInt();
		arlemiteBootsID = config.getItem("ArlemiteBoots", 3433).getInt();
		rupeeHelmetID = config.getItem("RupeeHelmet", 3434).getInt();
		rupeeBodyID = config.getItem("RupeeBody", 3435).getInt();
		rupeeLegsID = config.getItem("RupeeLegs", 3436).getInt();
		rupeeBootsID = config.getItem("RupeeBoots", 3437).getInt();
		infernalFlameID = config.getItem("InfernalFlame", 3438).getInt();
		
		baseSpawnCrystalID = config.getItem("BaseSpawn", 3439).getInt();
		SoulFiendSpawnCrystalID = config.getItem("SoulFiendSpawn", 3440).getInt();
		VamacheronSpawnCrystalID = config.getItem("VamacheronSpawn", 3441).getInt();
		TwilightDemonSpawnCrystalID = config.getItem("TwilightDemonSpawn", 3442).getInt();
		KarotSpawnCrystalID = config.getItem("KarotSpawn", 3443).getInt();
		DensosSpawnCrystalID = config.getItem("DensosSpawn", 3444).getInt();
		
		hordeHornID = config.getItem("HordeHorn", 3445).getInt();
		mysteriousClockID = config.getItem("MysteriousClock", 3446).getInt();
		watchingEyeID = config.getItem("WatchingEye", 3447).getInt();
		callOfTheWatcherID = config.getItem("CallOfTheWatcher", 3448).getInt();
		furyFireID = config.getItem("FuryFire", 3449).getInt();
		
		shadowHelmetID = config.getItem("ShadowHelmet", 3450).getInt();
		shadowBodyID = config.getItem("ShadowBody", 3451).getInt();
		shadowLegsID = config.getItem("ShadowLegs", 3452).getInt();
		shadowBootsID = config.getItem("ShadowBoots", 3453).getInt();
		aquaticHelmetID = config.getItem("AquaticHelmet", 3454).getInt();
		aquaticBodyID = config.getItem("AquaticBody", 3455).getInt();
		aquaticLegsID = config.getItem("AquaticLegs", 3456).getInt();
		aquaticBootsID = config.getItem("AquaticBoots", 3457).getInt();
		krakenSkinID = config.getItem("KrakenSkin", 3458).getInt();
		krakenScaleID = config.getItem("KrakenScale", 3459).getInt();
		shadowStoneID = config.getItem("ShadowStone", 3460).getInt();
		homeTeleporterID = config.getItem("HomeTeleporter", 3461).getInt();
		
		whaleFinID = config.getItem("WhaleFin", 3462).getInt();
		purpleGlowTreeID = config.getItem("PurpleGlowTree", 3463).getInt();
		pinkGlowTreeID = config.getItem("PinkGlowTree", 3464).getInt();
		eliteRealHelmID = config.getItem("EliteRealHelm", 3465).getInt();
		eliteRealBodyID = config.getItem("EliteRealBody", 3466).getInt();
		eliteRealLegsID = config.getItem("EliteRealLegs", 3467).getInt();
		eliteRealBootsID = config.getItem("EliteRealBoots", 3468).getInt();
		krakenHelmID = config.getItem("KrakenHelm", 3469).getInt();
		krakenBodyID = config.getItem("KrakenBody", 3470).getInt();
		krakenLegsID = config.getItem("KrakenLegs", 3471).getInt();
		krakenBootsID = config.getItem("KrakenBoots", 3472).getInt();
		divineStickID = config.getItem("DivineStick", 3473).getInt();
		divineWoodAxeID = config.getItem("DivineWoodAxe", 3474).getInt();
		divineWoodPickID = config.getItem("DivieWoodPick", 3475).getInt();
		divineWoodHoeID = config.getItem("DivineWoodHoe", 3476).getInt();
		divineWoodShovelID = config.getItem("DivineWoodShovel", 3477).getInt();
		divineWoodSwordID = config.getItem("DivineWoodSword", 3478).getInt();
		cyclopseEyeID = config.getItem("CyclopseEye", 3479).getInt();
		cyclopseBowID = config.getItem("CyclopseBow", 3480).getInt();
		cyclopseStaffID = config.getItem("CyclopianStaff", 3481).getInt();
		cyclopseSwordID = config.getItem("CyclopianSword", 3482).getInt();

		TwilightAppleID = config.getItem("TwilightApple", 3483).getInt();
		
		
		//ID = config.getItem("", 3485).getInt();

		config.save();
		}
}
